In [1]:
#importing libraries
import selenium
import pandas as pd
from selenium import webdriver
from time import sleep
import re

#importing requires exceptions which needs to handled
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException
from selenium.webdriver.common.by import By
from selenium.common.exceptions import ElementClickInterceptedException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [109]:
#automating chrome browser
driver=webdriver.Chrome()
driver.get("https://www.nobroker.in/")
driver.maximize_window()

In [94]:
buy_button=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[1]/div[3]/div[1]')
buy_button.click()

In [95]:

# creating empty lists
s_no = []
BHK_type = []
property_type = []
beds = []
bath = []
balcony = []
address = []
city = []
state_code = []
country = []
landmark = []
carpet_area = []
status = []
floor = []
transaction_type = []
year_built = []
price_per_square_feet = []
furnished_status = []
facing = []
car_parking = []
type_of_ownership = []
booking_amount = []
buy_total_price = []

In [89]:
len(bath)

0

In [81]:
#Bangalore City
#WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"/html/body/section/div[1]/form/div[2]/input[1]")))

#finding and sending Noida input the search input box
first_click=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
first_click.click()
sleep(2)
#sending city name in the search box
city=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
city.send_keys('HSR')
search_button=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/button")
search_button.click()

In [96]:
#collecting urls of properties
urls=[]
#for page change
#for i in range(1,13):
   # print('Scraping page',i)
for _ in range(15):
    driver.execute_script("window.scrollBy(0,300)")
    try:
    #scraping urls 
        WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a")))
        try:
            for url in driver.find_elements(By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a"):
                urls.append(url.get_attribute('href'))
        except StaleElementReferenceException:
            print('Append error')
        #WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//a[@data-page='next']")))
        #next_button=driver.find_element(By.XPATH,"//a[@data-page='next']")
        #next_button.click()
   
    except NoSuchElementException:
        print('scraping done')

driver.quit()

In [97]:
len(urls)

375

In [100]:
for i in urls:  # Iterating each and every URL to fetch full details
    driver.get(i)  # Taking each URL one by one as an input
    sleep(1)

    # BHK_type 
    try:
        beds_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[1]/div[2]/span/h4')
        bed_text = beds_.text.replace('Bedroom', '').strip()
        BHK_type.append(bed_text)
    except:
        BHK_type.append('None')

    # Bathroom
    try:
        bath_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[3]/div[2]/span/h4')
        bath_text = bath_.text.replace('Bathroom', '').strip()
        bath.append(bath_text)
    except:
        bath.append('None')

    # Carpet area
    try:
        cart_area = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[6]/div[3]/h5')
        if 'Sq.Ft' in cart_area.text:
            carpet_area_ = cart_area.text.replace(' Sq.Ft', '').replace(',', '')  # Remove ' Sq.Ft' and commas
            carpet_area.append(carpet_area_)
        else:
            carpet_area.append('None')
    except:
        carpet_area.append('None')

    # Price per square feet
    try:
        PRSF = driver.find_element(By.XPATH, '//div[@class="flexbox hidden-mobile"]/div[5]/div[1]')
        price_per_square_feet.append(PRSF.text)
    except:
        price_per_square_feet.append('None')

    # Property_Type
    try:
        Pro_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[6]/div[2]/span/h4')
        property_type.append(Pro_.text)
    except:
        property_type.append('None')

    # Status
    try:
        sta = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[4]/div[2]/span/h4')
        status.append(sta.text)
    except:
        status.append('None')

    # Year Built
    try:
        Year = driver.find_element(By.XPATH, '//div[@class="outer-parameters-block"]/ul/li[10]/div[2]')
        year_text = Year.text.strip()
        
        if year_text.isdigit() and len(year_text) == 4:
            year_built.append(int(year_text))
        else:
            year_built.append('None')  # Append 'None' if not a valid year
    except:
        year_built.append('None')

    # Landmarks
    try:
        land = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[3]/div/div/span[2]/a[1]')
        landmark.append(land.text)
    except:
        landmark.append('None')

    # Balcony
    try:
        Balc = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[5]/div[2]/span/h4')
        if Balc.text.strip().upper() == 'NA':
            balcony.append('None')
        else:
            balcony.append(Balc.text.strip())
    except:
        balcony.append('None')

    # Address
    try:
        Addr = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[2]/div[1]/h5')
        address.append(Addr.text)
    except:
        address.append('None')

    # City
    try:
        city_ = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        city_text = city_.text.split(',')[0]  # Split the text by comma and get the first part
        city.append(city_text)
    except:
        city.append('Bangalore')  
    # State_code
    try:
        State_cod = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        State_code_ = State_cod.text.split(',')[1].strip()  # Split the text by comma and get the second part
        state_code.append(State_code_)
    except:
        state_code.append('KA')  # Default state code assumed as 'KA'

    # Country
    try:
        Addr = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        country.append(Addr.text)
    except:
        country.append('India')  # Default country assumed as 'India'

    # Floor
    try:
        fl = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[9]/div[3]/h5')
        if '/' in fl.text:
            floor.append(fl.text)
        else:
            floor.append('None')
    except:
        floor.append('None')

    # Transaction type
    try:
        trans = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        transaction_type.append(trans.text)
    except:
        transaction_type.append('None')

    # Furnished status
    try:
        furnish = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[7]/div[3]/h5')
        if 'Fully Furnished' in furnish.text or 'Semi' in furnish.text:
            furnished_status.append(furnish.text)
        else:
            furnished_status.append('None')
    except:
        furnished_status.append('None')

    # Facing
    try:
        fac = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[8]/div[3]/h5')
        fac_text = fac.text.lower()  # Convert text to lowercase for case insensitivity
    
        if 'north-east' in fac_text or 'northeast' in fac_text:
            facing.append('northeast')
        elif 'south-east' in fac_text or 'southeast' in fac_text:
            facing.append('southeast')
        elif 'south-west' in fac_text or 'southwest' in fac_text:
            facing.append('southwest')
        elif 'north-west' in fac_text or 'northwest' in fac_text:
            facing.append('northwest')
        elif 'north' in fac_text:
            facing.append('North')
        elif 'east' in fac_text:
            facing.append('East')
        elif 'south' in fac_text:
            facing.append('South')
        elif 'west' in fac_text:
            facing.append('West')
        else:
            facing.append('None')
    except:
        facing.append('None')

    # Car Parking
    try:
        Car_Par = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[7]/div[2]/span/h4')
        car_parking.append(Car_Par.text)
    except:
        car_parking.append('None')

    # Type of ownership
    try:
        Type_of_owners = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[2]/div[3]/h5')
        type_of_ownership.append(Type_of_owners.text)
    except:
        type_of_ownership.append('None')

    # Booking amount
    try:
        booking = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        booking_amount.append(booking.text)
    except:
        booking_amount.append('None')

    
    # Buy total price
    CRORE_TO_THOUSAND = 10000000
    LAC_TO_THOUSAND = 100000

    def convert_price_to_thousands(price_text):
        if 'Crores' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Crores', '').strip())
            price_in_thousands = price_value * CRORE_TO_THOUSAND
        elif 'Lacs' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Lacs', '').strip())
            price_in_thousands = price_value * LAC_TO_THOUSAND
        else:
            price_in_thousands = float(price_text.replace('₹', '').strip())
        return price_in_thousands

    try:
        buy_t = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[3]/div[1]/div/div[1]/span')
        price_text = buy_t.text
        price_in_thousands = convert_price_to_thousands(price_text)
        buy_total_price.append(f'{round(price_in_thousands)}') 
    except:
        buy_total_price.append('None')
    
# Quit WebDriver
driver.quit()

In [110]:
df1=pd.DataFrame({
    "BHK_type": BHK_type,
    "Beds": BHK_type,
    "Bathroom": bath,
    "Carpet_area": carpet_area,
    "Price_per_square_feet": price_per_square_feet,
    "Property_Type": property_type,
    "Status": status,
    "Year_Built": year_built,
    "Landmarks": landmark,
    "Balcony": balcony,
    "Address": address,
    "City": city,
    "State_Code": state_code,
    "Country": country,
    "Floor": floor,
    "Transaction_Type": transaction_type,
    "Furnished_Status": furnished_status,
    "Facing": facing,
    "Car_Parking": car_parking,
    "Type_of_Ownership": type_of_ownership,
    "Booking_Amount": booking_amount,
    "Buy_Total_Price": buy_total_price
})

In [111]:
df1

,BHK_type,Beds,Bathroom,Carpet_area,Price_per_square_feet,Property_Type,Status,Year_Built,Landmarks,Balcony,...,State_Code,Country,Floor,Transaction_Type,Furnished_Status,Facing,Car_Parking,Type_of_Ownership,Booking_Amount,Buy_Total_Price
0,2,2,2,None,None,Sapthagiri Palace,"Jun 25, 2024",None,H S R Layout (Pickup Van/Bus),2,...,KA,India,None,None,None,None,Car,Self Owned,None,5300000
1,3,3,2,1300,None,Pjc Royale Arcadia,"Jun 29, 2024",None,Narasimha Chitramandira,2,...,KA,India,4/5,None,None,North,Bike and Car,Self Owned,None,19000000
2,3,3,3,None,None,Nd Sepal,"Jun 27, 2024",None,Barbeque Nation,2,...,KA,India,None,None,None,None,Bike and Car,Self Owned,None,10500000
3,4,4,17,None,None,Standalone Building,"Jun 25, 2024",None,Narasimha Chitramandira,8,...,KA,India,None,None,None,None,Car,Self Owned,None,53000000
4,4,4,7,None,None,Independent House,"Jul 6, 2024",None,Barbeque Nation,2,...,KA,India,None,None,None,None,Bike and Car,Self Owned,None,37500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,3,3,2,1200,None,Glin Grand,"Jun 30, 2026",None,Barbeque Nation,2,...,KA,India,1/4,None,None,East,Bike and Car,Self Owned,None,13700000
371,3,3,2,1200,None,Klin Royal,"May 8, 2026",None,Barbeque Nation,2,...,KA,India,1/4,None,None,East,Bike and Car,Self Owned,None,13800000
372,2,2,2,980,None,Riveriya Royale,"Mar 19, 2026",None,The Fisherman'S Wharf,1,...,KA,India,2/4,None,None,East,Bike and Car,Self Owned,None,11000000
373,1,1,1,None,None,Inner Spaces Orchar...,Immediately,None,H S R Layout (Pickup Van/Bus),1,...,KA,India,None,None,None,None,Bike and Car,Self Owned,None,8500000
374,2,2,2,1008,None,Srinivasa Sai Poorn...,Immediately,None,None,1,...,KA,India,1/3,None,Fully Furnished,South,Car,Self Owned,None,7560000

In [112]:
df1.to_csv('Bangalore.csv', index=False)

In [128]:
#automating chrome browser
driver=webdriver.Chrome()
driver.get("https://www.nobroker.in/")
driver.maximize_window()

In [120]:
buy_button=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[1]/div[3]/div[1]')
buy_button.click()

In [115]:
#Gurgaon City
#WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"/html/body/section/div[1]/form/div[2]/input[1]")))

#finding and sending Noida input the search input box
first_click=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
first_click.click()
sleep(2)
#sending city name in the search box
city=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
city.send_keys('gurgaon')
search_button=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/button")
search_button.click()

In [121]:
# creating empty lists
s_no = []
BHK_type = []
property_type = []
beds = []
bath = []
balcony = []
address = []
city = []
state_code = []
country = []
landmark = []
carpet_area = []
status = []
floor = []
transaction_type = []
year_built = []
price_per_square_feet = []
furnished_status = []
facing = []
car_parking = []
type_of_ownership = []
booking_amount = []
buy_total_price = []

In [125]:
#collecting urls of properties
urls=[]
#for page change
#for i in range(1,13):
   # print('Scraping page',i)
for _ in range(10):
    driver.execute_script("window.scrollBy(0,200)")
    try:
    #scraping urls 
        WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a")))
        try:
            for url in driver.find_elements(By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a"):
                urls.append(url.get_attribute('href'))
        except StaleElementReferenceException:
            print('Append error')
        #WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//a[@data-page='next']")))
        #next_button=driver.find_element(By.XPATH,"//a[@data-page='next']")
        #next_button.click()
   
    except NoSuchElementException:
        print('scraping done')

driver.quit()

In [126]:
len(urls)

360

In [129]:
for i in urls:  # Iterating each and every URL to fetch full details
    driver.get(i)  # Taking each URL one by one as an input
    sleep(1)

    # BHK_type 
    try:
        beds_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[1]/div[2]/span/h4')
        bed_text = beds_.text.replace('Bedroom', '').strip()
        BHK_type.append(bed_text)
    except:
        BHK_type.append('None')

    # Bathroom
    try:
        bath_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[3]/div[2]/span/h4')
        bath_text = bath_.text.replace('Bathroom', '').strip()
        bath.append(bath_text)
    except:
        bath.append('None')

    # Carpet area
    try:
        cart_area = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[6]/div[3]/h5')
        if 'Sq.Ft' in cart_area.text:
            carpet_area_ = cart_area.text.replace(' Sq.Ft', '').replace(',', '')  # Remove ' Sq.Ft' and commas
            carpet_area.append(carpet_area_)
        else:
            carpet_area.append('None')
    except:
        carpet_area.append('None')

    # Price per square feet
    try:
        PRSF = driver.find_element(By.XPATH, '//div[@class="flexbox hidden-mobile"]/div[5]/div[1]')
        price_per_square_feet.append(PRSF.text)
    except:
        price_per_square_feet.append('None')

    # Property_Type
    try:
        Pro_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[6]/div[2]/span/h4')
        property_type.append(Pro_.text)
    except:
        property_type.append('None')

    # Status
    try:
        sta = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[4]/div[2]/span/h4')
        status.append(sta.text)
    except:
        status.append('None')

    # Year Built
    try:
        Year = driver.find_element(By.XPATH, '//div[@class="outer-parameters-block"]/ul/li[10]/div[2]')
        year_text = Year.text.strip()
        
        if year_text.isdigit() and len(year_text) == 4:
            year_built.append(int(year_text))
        else:
            year_built.append('None')  # Append 'None' if not a valid year
    except:
        year_built.append('None')

    # Landmarks
    try:
        land = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[3]/div/div/span[2]/a[1]')
        landmark.append(land.text)
    except:
        landmark.append('None')

    # Balcony
    try:
        Balc = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[5]/div[2]/span/h4')
        if Balc.text.strip().upper() == 'NA':
            balcony.append('None')
        else:
            balcony.append(Balc.text.strip())
    except:
        balcony.append('None')

    # Address
    try:
        Addr = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[2]/div[1]/h5')
        address.append(Addr.text)
    except:
        address.append('None')

    # City
    try:
        city_ = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        city_text = city_.text.split(',')[0]  # Split the text by comma and get the first part
        city.append(city_text)
    except:
        city.append('Gurgaon')  
    # State_code
    try:
        State_cod = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        State_code_ = State_cod.text.split(',')[1].strip()  # Split the text by comma and get the second part
        state_code.append(State_code_)
    except:
        state_code.append('HR')  # Default state code assumed as 'KA'

    # Country
    try:
        Addr = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        country.append(Addr.text)
    except:
        country.append('India')  # Default country assumed as 'India'

    # Floor
    try:
        fl = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[9]/div[3]/h5')
        if '/' in fl.text:
            floor.append(fl.text)
        else:
            floor.append('None')
    except:
        floor.append('None')

    # Transaction type
    try:
        trans = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        transaction_type.append(trans.text)
    except:
        transaction_type.append('None')

    # Furnished status
    try:
        furnish = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[7]/div[3]/h5')
        if 'Fully Furnished' in furnish.text or 'Semi' in furnish.text:
            furnished_status.append(furnish.text)
        else:
            furnished_status.append('None')
    except:
        furnished_status.append('None')

    # Facing
    try:
        fac = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[8]/div[3]/h5')
        fac_text = fac.text.lower()  # Convert text to lowercase for case insensitivity
    
        if 'north-east' in fac_text or 'northeast' in fac_text:
            facing.append('northeast')
        elif 'south-east' in fac_text or 'southeast' in fac_text:
            facing.append('southeast')
        elif 'south-west' in fac_text or 'southwest' in fac_text:
            facing.append('southwest')
        elif 'north-west' in fac_text or 'northwest' in fac_text:
            facing.append('northwest')
        elif 'north' in fac_text:
            facing.append('North')
        elif 'east' in fac_text:
            facing.append('East')
        elif 'south' in fac_text:
            facing.append('South')
        elif 'west' in fac_text:
            facing.append('West')
        else:
            facing.append('None')
    except:
        facing.append('None')

    # Car Parking
    try:
        Car_Par = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[7]/div[2]/span/h4')
        car_parking.append(Car_Par.text)
    except:
        car_parking.append('None')

    # Type of ownership
    try:
        Type_of_owners = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[2]/div[3]/h5')
        type_of_ownership.append(Type_of_owners.text)
    except:
        type_of_ownership.append('None')

    # Booking amount
    try:
        booking = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        booking_amount.append(booking.text)
    except:
        booking_amount.append('None')

    
    # Buy total price
    CRORE_TO_THOUSAND = 10000000
    LAC_TO_THOUSAND = 100000

    def convert_price_to_thousands(price_text):
        if 'Crores' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Crores', '').strip())
            price_in_thousands = price_value * CRORE_TO_THOUSAND
        elif 'Lacs' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Lacs', '').strip())
            price_in_thousands = price_value * LAC_TO_THOUSAND
        else:
            price_in_thousands = float(price_text.replace('₹', '').strip())
        return price_in_thousands

    try:
        buy_t = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[3]/div[1]/div/div[1]/span')
        price_text = buy_t.text
        price_in_thousands = convert_price_to_thousands(price_text)
        buy_total_price.append(f'{round(price_in_thousands)}') 
    except:
        buy_total_price.append('None')
    
# Quit WebDriver
driver.quit()

In [130]:
df2=pd.DataFrame({
    "BHK_type": BHK_type,
    "Beds": BHK_type,
    "Bathroom": bath,
    "Carpet_area": carpet_area,
    "Price_per_square_feet": price_per_square_feet,
    "Property_Type": property_type,
    "Status": status,
    "Year_Built": year_built,
    "Landmarks": landmark,
    "Balcony": balcony,
    "Address": address,
    "City": city,
    "State_Code": state_code,
    "Country": country,
    "Floor": floor,
    "Transaction_Type": transaction_type,
    "Furnished_Status": furnished_status,
    "Facing": facing,
    "Car_Parking": car_parking,
    "Type_of_Ownership": type_of_ownership,
    "Booking_Amount": booking_amount,
    "Buy_Total_Price": buy_total_price
})

In [131]:
df2

,BHK_type,Beds,Bathroom,Carpet_area,Price_per_square_feet,Property_Type,Status,Year_Built,Landmarks,Balcony,...,State_Code,Country,Floor,Transaction_Type,Furnished_Status,Facing,Car_Parking,Type_of_Ownership,Booking_Amount,Buy_Total_Price
0,4,4,4,None,None,Independent House,Immediately,None,Millennium City Centre Gurugram,2,...,HR,India,None,None,None,None,Car,Self Owned,None,28000000
1,4,4,2,None,None,Standalone Building,Immediately,None,Millennium City Centre Gurugram,None,...,HR,India,None,None,None,None,None,Self Owned,None,3200000
2,4,4,18,None,None,Standalone Building,Immediately,None,Eros Corporate Park,None,...,HR,India,None,None,None,None,Bike,Self Owned,None,55000000
3,3,3,4,None,None,"Orchid Petals, Orch...",Immediately,None,Eros Corporate Park,3,...,HR,India,None,None,None,None,Car,Self Owned,None,33500000
4,2,2,2,None,None,Divya Apartment,Immediately,None,Eros Corporate Park,None,...,HR,India,None,None,None,None,Bike and Car,Self Owned,None,5800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,3,3,3,None,None,Apartment,Immediately,None,Millennium City Centre Gurugram,None,...,HR,India,None,None,None,None,Bike,Self Owned,None,11000000
356,4,4,5,None,None,Independent House,Immediately,None,Harish Bakery,None,...,HR,India,None,None,None,None,Bike,Self Owned,None,9200000
357,2,2,2,None,None,Independent House,Immediately,None,Harish Bakery,None,...,HR,India,None,None,None,None,Bike,Self Owned,None,9200000
358,3,3,3,None,None,Independent House,"Jul 25, 2024",None,Eros Corporate Park,None,...,HR,India,None,None,None,None,Bike,Self Owned,None,4500000
359,4,4,4,None,None,Independent House,Immediately,None,Eros Corporate Park,None,...,HR,India,None,None,None,None,Bike and Car,Self Owned,None,9600000

In [132]:
df2.to_csv('Gurgaon.csv', index=False)

In [154]:
#automating chrome browser
driver=webdriver.Chrome()
driver.get("https://www.nobroker.in/")
driver.maximize_window()

In [150]:
buy_button=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[1]/div[3]/div[1]')
buy_button.click()

In [136]:
#Delhi City
#WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"/html/body/section/div[1]/form/div[2]/input[1]")))

#finding and sending Noida input the search input box
first_click=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
first_click.click()
sleep(2)
#sending city name in the search box
city=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
city.send_keys('delhi')
search_button=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/button")
search_button.click()

In [137]:
# creating empty lists
s_no = []
BHK_type = []
property_type = []
beds = []
bath = []
balcony = []
address = []
city = []
state_code = []
country = []
landmark = []
carpet_area = []
status = []
floor = []
transaction_type = []
year_built = []
price_per_square_feet = []
furnished_status = []
facing = []
car_parking = []
type_of_ownership = []
booking_amount = []
buy_total_price = []

In [152]:
#collecting urls of properties
urls=[]
#for page scrolling
#for i in range(1,13):
   # print('Scraping page',i)
for _ in range(15):
    driver.execute_script("window.scrollBy(0,300)")
    try:
    #scraping urls 
        WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a")))
        try:
            for url in driver.find_elements(By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a"):
                urls.append(url.get_attribute('href'))
        except StaleElementReferenceException:
            print('Append error')
        #WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//a[@data-page='next']")))
        #next_button=driver.find_element(By.XPATH,"//a[@data-page='next']")
        #next_button.click()
   
    except NoSuchElementException:
        print('scraping done')

driver.quit()

In [153]:
len(urls)

375

In [155]:
for i in urls:  # Iterating each and every URL to fetch full details
    driver.get(i)  # Taking each URL one by one as an input
    sleep(1)

    # BHK_type 
    try:
        beds_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[1]/div[2]/span/h4')
        bed_text = beds_.text.replace('Bedroom', '').strip()
        BHK_type.append(bed_text)
    except:
        BHK_type.append('None')

    # Bathroom
    try:
        bath_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[3]/div[2]/span/h4')
        bath_text = bath_.text.replace('Bathroom', '').strip()
        bath.append(bath_text)
    except:
        bath.append('None')

    # Carpet area
    try:
        cart_area = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[6]/div[3]/h5')
        if 'Sq.Ft' in cart_area.text:
            carpet_area_ = cart_area.text.replace(' Sq.Ft', '').replace(',', '')  # Remove ' Sq.Ft' and commas
            carpet_area.append(carpet_area_)
        else:
            carpet_area.append('None')
    except:
        carpet_area.append('None')

    # Price per square feet
    try:
        PRSF = driver.find_element(By.XPATH, '//div[@class="flexbox hidden-mobile"]/div[5]/div[1]')
        price_per_square_feet.append(PRSF.text)
    except:
        price_per_square_feet.append('None')

    # Property_Type
    try:
        Pro_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[6]/div[2]/span/h4')
        property_type.append(Pro_.text)
    except:
        property_type.append('None')

    # Status
    try:
        sta = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[4]/div[2]/span/h4')
        status.append(sta.text)
    except:
        status.append('None')

    # Year Built
    try:
        Year = driver.find_element(By.XPATH, '//div[@class="outer-parameters-block"]/ul/li[10]/div[2]')
        year_text = Year.text.strip()
        
        if year_text.isdigit() and len(year_text) == 4:
            year_built.append(int(year_text))
        else:
            year_built.append('None')  # Append 'None' if not a valid year
    except:
        year_built.append('None')

    # Landmarks
    try:
        land = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[3]/div/div/span[2]/a[1]')
        landmark.append(land.text)
    except:
        landmark.append('None')

    # Balcony
    try:
        Balc = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[5]/div[2]/span/h4')
        if Balc.text.strip().upper() == 'NA':
            balcony.append('None')
        else:
            balcony.append(Balc.text.strip())
    except:
        balcony.append('None')

    # Address
    try:
        Addr = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[2]/div[1]/h5')
        address.append(Addr.text)
    except:
        address.append('None')

    # City
    try:
        city_ = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        city_text = city_.text.split(',')[0]  # Split the text by comma and get the first part
        city.append(city_text)
    except:
        city.append('Delhi')  
    # State_code
    try:
        State_cod = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        State_code_ = State_cod.text.split(',')[1].strip()  # Split the text by comma and get the second part
        state_code.append(State_code_)
    except:
        state_code.append('DL')  

    # Country
    try:
        Addr = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        country.append(Addr.text)
    except:
        country.append('India')  # Default country assumed as 'India'

    # Floor
    try:
        fl = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[9]/div[3]/h5')
        if '/' in fl.text:
            floor.append(fl.text)
        else:
            floor.append('None')
    except:
        floor.append('None')

    # Transaction type
    try:
        trans = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        transaction_type.append(trans.text)
    except:
        transaction_type.append('None')

    # Furnished status
    try:
        furnish = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[7]/div[3]/h5')
        if 'Fully Furnished' in furnish.text or 'Semi' in furnish.text:
            furnished_status.append(furnish.text)
        else:
            furnished_status.append('None')
    except:
        furnished_status.append('None')

    # Facing
    try:
        fac = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[8]/div[3]/h5')
        fac_text = fac.text.lower()  # Convert text to lowercase for case insensitivity
    
        if 'north-east' in fac_text or 'northeast' in fac_text:
            facing.append('northeast')
        elif 'south-east' in fac_text or 'southeast' in fac_text:
            facing.append('southeast')
        elif 'south-west' in fac_text or 'southwest' in fac_text:
            facing.append('southwest')
        elif 'north-west' in fac_text or 'northwest' in fac_text:
            facing.append('northwest')
        elif 'north' in fac_text:
            facing.append('North')
        elif 'east' in fac_text:
            facing.append('East')
        elif 'south' in fac_text:
            facing.append('South')
        elif 'west' in fac_text:
            facing.append('West')
        else:
            facing.append('None')
    except:
        facing.append('None')

    # Car Parking
    try:
        Car_Par = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[7]/div[2]/span/h4')
        car_parking.append(Car_Par.text)
    except:
        car_parking.append('None')

    # Type of ownership
    try:
        Type_of_owners = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[2]/div[3]/h5')
        type_of_ownership.append(Type_of_owners.text)
    except:
        type_of_ownership.append('None')

    # Booking amount
    try:
        booking = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        booking_amount.append(booking.text)
    except:
        booking_amount.append('None')

    
    # Buy total price
    CRORE_TO_THOUSAND = 10000000
    LAC_TO_THOUSAND = 100000

    def convert_price_to_thousands(price_text):
        if 'Crores' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Crores', '').strip())
            price_in_thousands = price_value * CRORE_TO_THOUSAND
        elif 'Lacs' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Lacs', '').strip())
            price_in_thousands = price_value * LAC_TO_THOUSAND
        else:
            price_in_thousands = float(price_text.replace('₹', '').strip())
        return price_in_thousands

    try:
        buy_t = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[3]/div[1]/div/div[1]/span')
        price_text = buy_t.text
        price_in_thousands = convert_price_to_thousands(price_text)
        buy_total_price.append(f'{round(price_in_thousands)}') 
    except:
        buy_total_price.append('None')
    
# Quit WebDriver
driver.quit()

In [156]:
df3=pd.DataFrame({
    "BHK_type": BHK_type,
    "Beds": BHK_type,
    "Bathroom": bath,
    "Carpet_area": carpet_area,
    "Price_per_square_feet": price_per_square_feet,
    "Property_Type": property_type,
    "Status": status,
    "Year_Built": year_built,
    "Landmarks": landmark,
    "Balcony": balcony,
    "Address": address,
    "City": city,
    "State_Code": state_code,
    "Country": country,
    "Floor": floor,
    "Transaction_Type": transaction_type,
    "Furnished_Status": furnished_status,
    "Facing": facing,
    "Car_Parking": car_parking,
    "Type_of_Ownership": type_of_ownership,
    "Booking_Amount": booking_amount,
    "Buy_Total_Price": buy_total_price
})

In [157]:
df3

,BHK_type,Beds,Bathroom,Carpet_area,Price_per_square_feet,Property_Type,Status,Year_Built,Landmarks,Balcony,...,State_Code,Country,Floor,Transaction_Type,Furnished_Status,Facing,Car_Parking,Type_of_Ownership,Booking_Amount,Buy_Total_Price
0,2,2,2,None,None,Standalone Building,Immediately,None,Vaishro Chat Bhandar,None,...,DL,India,None,None,None,None,Bike and Car,Self Owned,None,3500000
1,2,2,1,None,None,Standalone Building,Immediately,None,Vaishro Chat Bhandar,None,...,DL,India,None,None,None,None,None,Self Owned,None,4000000
2,3,3,3,None,None,Standalone Building,Immediately,None,Vaishro Chat Bhandar,None,...,DL,India,None,None,None,None,Bike and Car,Self Owned,None,5500000
3,2,2,1,None,None,Standalone Building,Immediately,None,Vaishro Chat Bhandar,None,...,DL,India,None,None,None,None,Bike,Self Owned,None,5800000
4,2,2,1,None,None,Standalone Building,Immediately,None,Vaishro Chat Bhandar,None,...,DL,India,None,None,None,None,None,Self Owned,None,6000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,1,1,1,None,None,Standalone Building,Immediately,None,Tom Uncle Maggi Point,2,...,DL,India,None,None,None,None,Bike,Self Owned,None,2450000
371,2,2,2,None,None,Standalone Building,Immediately,None,Tom Uncle Maggi Point,1,...,DL,India,None,None,None,None,Bike,Self Owned,None,5700000
372,2,2,1,None,None,Apartment,Immediately,None,Filmistan Cinema,None,...,DL,India,None,None,None,None,Bike and Car,Self Owned,None,4700000
373,2,2,1,800,None,Standalone Building,Immediately,None,Vaishro Chat Bhandar,1,...,DL,India,2/3,None,Semi,South,Bike and Car,Self Owned,None,4000000
374,1,1,1,None,None,Standalone Building,Immediately,None,Vaishro Chat Bhandar,None,...,DL,India,None,None,None,None,None,Self Owned,None,3000000

In [158]:
df3.to_csv('Delhi.csv', index=False)

In [176]:
#automating chrome browser
driver=webdriver.Chrome()
driver.get("https://www.nobroker.in/")
driver.maximize_window()

In [160]:
buy_button=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[1]/div[3]/div[1]')
buy_button.click()

In [161]:
#Chennai City
#WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"/html/body/section/div[1]/form/div[2]/input[1]")))

#finding and sending Noida input the search input box
first_click=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
first_click.click()
sleep(2)
#sending city name in the search box
city=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
city.send_keys('Chennai')
search_button=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/button")
search_button.click()

In [162]:
# creating empty lists
s_no = []
BHK_type = []
property_type = []
beds = []
bath = []
balcony = []
address = []
city = []
state_code = []
country = []
landmark = []
carpet_area = []
status = []
floor = []
transaction_type = []
year_built = []
price_per_square_feet = []
furnished_status = []
facing = []
car_parking = []
type_of_ownership = []
booking_amount = []
buy_total_price = []

In [174]:
#collecting urls of properties
urls=[]
#for page scrolling
#for i in range(1,13):
   # print('Scraping page',i)
for _ in range(10):
    driver.execute_script("window.scrollBy(0,100)")
    try:
    #scraping urls 
        WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a")))
        try:
            for url in driver.find_elements(By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a"):
                urls.append(url.get_attribute('href'))
        except StaleElementReferenceException:
            print('Append error')
        #WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//a[@data-page='next']")))
        #next_button=driver.find_element(By.XPATH,"//a[@data-page='next']")
        #next_button.click()
   
    except NoSuchElementException:
        print('scraping done')

driver.quit()

In [175]:
len(urls)

250

In [177]:
for i in urls:  # Iterating each and every URL to fetch full details
    driver.get(i)  # Taking each URL one by one as an input
    sleep(1)

    # BHK_type 
    try:
        beds_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[1]/div[2]/span/h4')
        bed_text = beds_.text.replace('Bedroom', '').strip()
        BHK_type.append(bed_text)
    except:
        BHK_type.append('None')

    # Bathroom
    try:
        bath_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[3]/div[2]/span/h4')
        bath_text = bath_.text.replace('Bathroom', '').strip()
        bath.append(bath_text)
    except:
        bath.append('None')

    # Carpet area
    try:
        cart_area = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[6]/div[3]/h5')
        if 'Sq.Ft' in cart_area.text:
            carpet_area_ = cart_area.text.replace(' Sq.Ft', '').replace(',', '')  # Remove ' Sq.Ft' and commas
            carpet_area.append(carpet_area_)
        else:
            carpet_area.append('None')
    except:
        carpet_area.append('None')

    # Price per square feet
    try:
        PRSF = driver.find_element(By.XPATH, '//div[@class="flexbox hidden-mobile"]/div[5]/div[1]')
        price_per_square_feet.append(PRSF.text)
    except:
        price_per_square_feet.append('None')

    # Property_Type
    try:
        Pro_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[6]/div[2]/span/h4')
        property_type.append(Pro_.text)
    except:
        property_type.append('None')

    # Status
    try:
        sta = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[4]/div[2]/span/h4')
        status.append(sta.text)
    except:
        status.append('None')

    # Year Built
    try:
        Year = driver.find_element(By.XPATH, '//div[@class="outer-parameters-block"]/ul/li[10]/div[2]')
        year_text = Year.text.strip()
        
        if year_text.isdigit() and len(year_text) == 4:
            year_built.append(int(year_text))
        else:
            year_built.append('None')  # Append 'None' if not a valid year
    except:
        year_built.append('None')

    # Landmarks
    try:
        land = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[3]/div/div/span[2]/a[1]')
        landmark.append(land.text)
    except:
        landmark.append('None')

    # Balcony
    try:
        Balc = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[5]/div[2]/span/h4')
        if Balc.text.strip().upper() == 'NA':
            balcony.append('None')
        else:
            balcony.append(Balc.text.strip())
    except:
        balcony.append('None')

    # Address
    try:
        Addr = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[2]/div[1]/h5')
        address.append(Addr.text)
    except:
        address.append('None')

    # City
    try:
        city_ = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        city_text = city_.text.split(',')[0]  # Split the text by comma and get the first part
        city.append(city_text)
    except:
        city.append('Chennai')  
        
    # State_code
    try:
        State_cod = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        State_code_ = State_cod.text.split(',')[1].strip()  # Split the text by comma and get the second part
        state_code.append(State_code_)
    except:
        state_code.append('TN')  

    # Country
    try:
        Addr = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        country.append(Addr.text)
    except:
        country.append('India')  # Default country assumed as 'India'

    # Floor
    try:
        fl = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[9]/div[3]/h5')
        if '/' in fl.text:
            floor.append(fl.text)
        else:
            floor.append('None')
    except:
        floor.append('None')

    # Transaction type
    try:
        trans = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        transaction_type.append(trans.text)
    except:
        transaction_type.append('None')

    # Furnished status
    try:
        furnish = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[7]/div[3]/h5')
        if 'Fully Furnished' in furnish.text or 'Semi' in furnish.text:
            furnished_status.append(furnish.text)
        else:
            furnished_status.append('None')
    except:
        furnished_status.append('None')

    # Facing
    try:
        fac = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[8]/div[3]/h5')
        fac_text = fac.text.lower()  # Convert text to lowercase for case insensitivity
    
        if 'north-east' in fac_text or 'northeast' in fac_text:
            facing.append('northeast')
        elif 'south-east' in fac_text or 'southeast' in fac_text:
            facing.append('southeast')
        elif 'south-west' in fac_text or 'southwest' in fac_text:
            facing.append('southwest')
        elif 'north-west' in fac_text or 'northwest' in fac_text:
            facing.append('northwest')
        elif 'north' in fac_text:
            facing.append('North')
        elif 'east' in fac_text:
            facing.append('East')
        elif 'south' in fac_text:
            facing.append('South')
        elif 'west' in fac_text:
            facing.append('West')
        else:
            facing.append('None')
    except:
        facing.append('None')

    # Car Parking
    try:
        Car_Par = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[7]/div[2]/span/h4')
        car_parking.append(Car_Par.text)
    except:
        car_parking.append('None')

    # Type of ownership
    try:
        Type_of_owners = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[2]/div[3]/h5')
        type_of_ownership.append(Type_of_owners.text)
    except:
        type_of_ownership.append('None')

    # Booking amount
    try:
        booking = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        booking_amount.append(booking.text)
    except:
        booking_amount.append('None')

    
    # Buy total price
    CRORE_TO_THOUSAND = 10000000
    LAC_TO_THOUSAND = 100000

    def convert_price_to_thousands(price_text):
        if 'Crores' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Crores', '').strip())
            price_in_thousands = price_value * CRORE_TO_THOUSAND
        elif 'Lacs' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Lacs', '').strip())
            price_in_thousands = price_value * LAC_TO_THOUSAND
        else:
            price_in_thousands = float(price_text.replace('₹', '').strip())
        return price_in_thousands

    try:
        buy_t = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[3]/div[1]/div/div[1]/span')
        price_text = buy_t.text
        price_in_thousands = convert_price_to_thousands(price_text)
        buy_total_price.append(f'{round(price_in_thousands)}') 
    except:
        buy_total_price.append('None')
    
# Quit WebDriver
driver.quit()

In [178]:
df4=pd.DataFrame({
   "BHK_type": BHK_type,
    "Beds": BHK_type,
    "Bathroom": bath,
    "Carpet_area": carpet_area,
    "Price_per_square_feet": price_per_square_feet,
    "Property_Type": property_type,
    "Status": status,
    "Year_Built": year_built,
    "Landmarks": landmark,
    "Balcony": balcony,
    "Address": address,
    "City": city,
    "State_Code": state_code,
    "Country": country,
    "Floor": floor,
    "Transaction_Type": transaction_type,
    "Furnished_Status": furnished_status,
    "Facing": facing,
    "Car_Parking": car_parking,
    "Type_of_Ownership": type_of_ownership,
    "Booking_Amount": booking_amount,
    "Buy_Total_Price": buy_total_price
})

In [179]:
df4

,BHK_type,Beds,Bathroom,Carpet_area,Price_per_square_feet,Property_Type,Status,Year_Built,Landmarks,Balcony,...,State_Code,Country,Floor,Transaction_Type,Furnished_Status,Facing,Car_Parking,Type_of_Ownership,Booking_Amount,Buy_Total_Price
0,3,3,2,None,None,Gl Embassy Towers,"Jun 28, 2024",None,Regus KRM - Chetpet,1,...,TN,India,None,None,None,None,Bike and Car,Self Owned,None,15000000
1,3,3,3,1680,None,Dlf Commanders Court,Immediately,None,Regus KRM - Chetpet,3,...,TN,India,10/16,None,Semi,North,Bike and Car,Self Owned,None,30000000
2,1,1,1,None,None,Independent House,Immediately,None,Spencer Plaza Mall,None,...,TN,India,None,None,None,None,None,Self Owned,None,5500000
3,3,3,3,None,None,Driver Street Pudup...,Immediately,None,Kodambakkam,2,...,TN,India,None,None,None,None,None,Self Owned,None,28000000
4,4,4,4,1549,None,Landmark Building,Immediately,None,Saravana Stores,2,...,TN,India,5/5,None,Fully Furnished,East,Car,Self Owned,None,21000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,3,3,4,1595,None,Amber Crest,Immediately,None,None,1,...,TN,India,4/4,None,Semi,northwest,Bike and Car,Self Owned,None,18000000
246,2,2,2,899,None,Halls Towers,Immediately,None,Regus KRM - Chetpet,1,...,TN,India,4/12,None,None,East,Bike and Car,Self Owned,None,6750000
247,3,3,4,None,None,Shivalaya Building,Immediately,None,Regus KRM - Chetpet,2,...,TN,India,None,None,None,None,Car,Self Owned,None,16500000
248,2,2,2,None,None,Standalone Building,Immediately,None,Regus KRM - Chetpet,None,...,TN,India,None,None,None,None,None,Self Owned,None,11600000
249,3,3,3,1400,None,Dlf Commanders Court,Immediately,None,Regus KRM - Chetpet,3,...,TN,India,13/17,None,Semi,East,Bike and Car,Self Owned,None,29500000

In [180]:
df4.to_csv('Chennai.csv', index=False)

In [187]:
#automating chrome browser
driver=webdriver.Chrome()
driver.get("https://www.nobroker.in/")
driver.maximize_window()

In [182]:
buy_button=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[1]/div[3]/div[1]')
buy_button.click()

In [183]:
#Pune City
#WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"/html/body/section/div[1]/form/div[2]/input[1]")))

#finding and sending Noida input the search input box
first_click=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
first_click.click()
sleep(2)
#sending city name in the search box
city=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
city.send_keys('Pune')
search_button=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/button")
search_button.click()

In [184]:
# creating empty lists
s_no = []
BHK_type = []
property_type = []
beds = []
bath = []
balcony = []
address = []
city = []
state_code = []
country = []
landmark = []
carpet_area = []
status = []
floor = []
transaction_type = []
year_built = []
price_per_square_feet = []
furnished_status = []
facing = []
car_parking = []
type_of_ownership = []
booking_amount = []
buy_total_price = []

In [185]:
#collecting urls of properties
urls=[]
#for page scrolling
#for i in range(1,13):
   # print('Scraping page',i)
for _ in range(9):
    driver.execute_script("window.scrollBy(0,200)")
    try:
    #scraping urls 
        WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a")))
        try:
            for url in driver.find_elements(By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a"):
                urls.append(url.get_attribute('href'))
        except StaleElementReferenceException:
            print('Append error')
        #WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//a[@data-page='next']")))
        #next_button=driver.find_element(By.XPATH,"//a[@data-page='next']")
        #next_button.click()
   
    except NoSuchElementException:
        print('scraping done')

driver.quit()

In [186]:
len(urls)

225

In [188]:
for i in urls:  # Iterating each and every URL to fetch full details
    driver.get(i)  # Taking each URL one by one as an input
    sleep(1)

    # BHK_type 
    try:
        beds_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[1]/div[2]/span/h4')
        bed_text = beds_.text.replace('Bedroom', '').strip()
        BHK_type.append(bed_text)
    except:
        BHK_type.append('None')

    # Bathroom
    try:
        bath_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[3]/div[2]/span/h4')
        bath_text = bath_.text.replace('Bathroom', '').strip()
        bath.append(bath_text)
    except:
        bath.append('None')

    # Carpet area
    try:
        cart_area = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[6]/div[3]/h5')
        if 'Sq.Ft' in cart_area.text:
            carpet_area_ = cart_area.text.replace(' Sq.Ft', '').replace(',', '')  # Remove ' Sq.Ft' and commas
            carpet_area.append(carpet_area_)
        else:
            carpet_area.append('None')
    except:
        carpet_area.append('None')

    # Price per square feet
    try:
        PRSF = driver.find_element(By.XPATH, '//div[@class="flexbox hidden-mobile"]/div[5]/div[1]')
        price_per_square_feet.append(PRSF.text)
    except:
        price_per_square_feet.append('None')

    # Property_Type
    try:
        Pro_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[6]/div[2]/span/h4')
        property_type.append(Pro_.text)
    except:
        property_type.append('None')

    # Status
    try:
        sta = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[4]/div[2]/span/h4')
        status.append(sta.text)
    except:
        status.append('None')

    # Year Built
    try:
        Year = driver.find_element(By.XPATH, '//div[@class="outer-parameters-block"]/ul/li[10]/div[2]')
        year_text = Year.text.strip()
        
        if year_text.isdigit() and len(year_text) == 4:
            year_built.append(int(year_text))
        else:
            year_built.append('None')  # Append 'None' if not a valid year
    except:
        year_built.append('None')

    # Landmarks
    try:
        land = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[3]/div/div/span[2]/a[1]')
        landmark.append(land.text)
    except:
        landmark.append('None')

    # Balcony
    try:
        Balc = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[5]/div[2]/span/h4')
        if Balc.text.strip().upper() == 'NA':
            balcony.append('None')
        else:
            balcony.append(Balc.text.strip())
    except:
        balcony.append('None')

    # Address
    try:
        Addr = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[2]/div[1]/h5')
        address.append(Addr.text)
    except:
        address.append('None')

    # City
    try:
        city_ = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        city_text = city_.text.split(',')[0]  # Split the text by comma and get the first part
        city.append(city_text)
    except:
        city.append('Pune')  
    # State_code
    try:
        State_cod = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        State_code_ = State_cod.text.split(',')[1].strip()  # Split the text by comma and get the second part
        state_code.append(State_code_)
    except:
        state_code.append('MH')  # Default state code assumed as 'KA'

    # Country
    try:
        Addr = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        country.append(Addr.text)
    except:
        country.append('India')  # Default country assumed as 'India'

    # Floor
    try:
        fl = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[9]/div[3]/h5')
        if '/' in fl.text:
            floor.append(fl.text)
        else:
            floor.append('None')
    except:
        floor.append('None')

    # Transaction type
    try:
        trans = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        transaction_type.append(trans.text)
    except:
        transaction_type.append('None')

    # Furnished status
    try:
        furnish = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[7]/div[3]/h5')
        if 'Fully Furnished' in furnish.text or 'Semi' in furnish.text:
            furnished_status.append(furnish.text)
        else:
            furnished_status.append('None')
    except:
        furnished_status.append('None')

    # Facing
    try:
        fac = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[8]/div[3]/h5')
        fac_text = fac.text.lower()  # Convert text to lowercase for case insensitivity
    
        if 'north-east' in fac_text or 'northeast' in fac_text:
            facing.append('northeast')
        elif 'south-east' in fac_text or 'southeast' in fac_text:
            facing.append('southeast')
        elif 'south-west' in fac_text or 'southwest' in fac_text:
            facing.append('southwest')
        elif 'north-west' in fac_text or 'northwest' in fac_text:
            facing.append('northwest')
        elif 'north' in fac_text:
            facing.append('North')
        elif 'east' in fac_text:
            facing.append('East')
        elif 'south' in fac_text:
            facing.append('South')
        elif 'west' in fac_text:
            facing.append('West')
        else:
            facing.append('None')
    except:
        facing.append('None')

    # Car Parking
    try:
        Car_Par = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[7]/div[2]/span/h4')
        car_parking.append(Car_Par.text)
    except:
        car_parking.append('None')

    # Type of ownership
    try:
        Type_of_owners = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[2]/div[3]/h5')
        type_of_ownership.append(Type_of_owners.text)
    except:
        type_of_ownership.append('None')

    # Booking amount
    try:
        booking = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        booking_amount.append(booking.text)
    except:
        booking_amount.append('None')

    
    # Buy total price
    CRORE_TO_THOUSAND = 10000000
    LAC_TO_THOUSAND = 100000

    def convert_price_to_thousands(price_text):
        if 'Crores' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Crores', '').strip())
            price_in_thousands = price_value * CRORE_TO_THOUSAND
        elif 'Lacs' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Lacs', '').strip())
            price_in_thousands = price_value * LAC_TO_THOUSAND
        else:
            price_in_thousands = float(price_text.replace('₹', '').strip())
        return price_in_thousands

    try:
        buy_t = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[3]/div[1]/div/div[1]/span')
        price_text = buy_t.text
        price_in_thousands = convert_price_to_thousands(price_text)
        buy_total_price.append(f'{round(price_in_thousands)}') 
    except:
        buy_total_price.append('None')
    
# Quit WebDriver
driver.quit()

In [189]:
df5=pd.DataFrame({
"BHK_type": BHK_type,
    "Beds": BHK_type,
    "Bathroom": bath,
    "Carpet_area": carpet_area,
    "Price_per_square_feet": price_per_square_feet,
    "Property_Type": property_type,
    "Status": status,
    "Year_Built": year_built,
    "Landmarks": landmark,
    "Balcony": balcony,
    "Address": address,
    "City": city,
    "State_Code": state_code,
    "Country": country,
    "Floor": floor,
    "Transaction_Type": transaction_type,
    "Furnished_Status": furnished_status,
    "Facing": facing,
    "Car_Parking": car_parking,
    "Type_of_Ownership": type_of_ownership,
    "Booking_Amount": booking_amount,
    "Buy_Total_Price": buy_total_price
})

In [190]:
df5

,BHK_type,Beds,Bathroom,Carpet_area,Price_per_square_feet,Property_Type,Status,Year_Built,Landmarks,Balcony,...,State_Code,Country,Floor,Transaction_Type,Furnished_Status,Facing,Car_Parking,Type_of_Ownership,Booking_Amount,Buy_Total_Price
0,2,2,2,None,None,Paramount Society,Immediately,None,Bibwewadi,None,...,MH,India,None,None,None,None,Bike and Car,Self Owned,None,8500000
1,3,3,3,None,None,Gulmohar Apartments,Immediately,None,Bibwewadi,1,...,MH,India,None,None,None,None,Bike and Car,Self Owned,None,13500000
2,3,3,3,None,None,Independent House,Immediately,None,None,3,...,MH,India,None,None,None,None,Car,Self Owned,None,23500000
3,2,2,3,None,None,Madhav Society,Immediately,None,Bibwewadi,1,...,MH,India,None,None,None,None,Bike and Car,Self Owned,None,11000000
4,2,2,2,None,None,Standalone Building,Immediately,None,Bibwewadi,1,...,MH,India,None,None,None,None,Car,Self Owned,None,8900000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,3,3,3,1200,None,Wonderland Shopping...,Immediately,None,SGS Mall,None,...,MH,India,1/6,None,Fully Furnished,North,Bike,Self Owned,None,14000000
221,2,2,2,1050,None,Cinderella Apartmen...,Immediately,None,SGS Mall,2,...,MH,India,5/6,None,Semi,East,None,Self Owned,None,12500000
222,1,1,1,500,None,Deccan Towers,Immediately,None,SGS Mall,1,...,MH,India,4/6,None,None,None,Bike and Car,Self Owned,None,3850000
223,4,4,3,1200,None,"House No. 1578, Bhi...",Immediately,None,SGS Mall,None,...,MH,India,0/2,None,None,North,None,Self Owned,None,5000000
224,1,1,2,None,None,Clover Center,Immediately,None,SGS Mall,2,...,MH,India,None,None,None,None,Bike,Self Owned,None,5700000

In [191]:
df5.to_csv('Pune.csv', index=False)

In [198]:
#automating chrome browser
driver=webdriver.Chrome()
driver.get("https://www.nobroker.in/")
driver.maximize_window()

In [193]:
buy_button=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[1]/div[3]/div[1]')
buy_button.click()

In [194]:
#Mumbai City
#WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"/html/body/section/div[1]/form/div[2]/input[1]")))

#finding and sending Noida input the search input box
first_click=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
first_click.click()
sleep(2)
#sending city name in the search box
city=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
city.send_keys('Thane')
search_button=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/button")
search_button.click()

In [195]:
# creating empty lists
s_no = []
BHK_type = []
property_type = []
beds = []
bath = []
balcony = []
address = []
city = []
state_code = []
country = []
landmark = []
carpet_area = []
status = []
floor = []
transaction_type = []
year_built = []
price_per_square_feet = []
furnished_status = []
facing = []
car_parking = []
type_of_ownership = []
booking_amount = []
buy_total_price = []

In [196]:
#collecting urls of properties
urls=[]
#for page scrolling
#for i in range(1,13):
   # print('Scraping page',i)
for _ in range(15):
    driver.execute_script("window.scrollBy(0,300)")
    try:
    #scraping urls 
        WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a")))
        try:
            for url in driver.find_elements(By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a"):
                urls.append(url.get_attribute('href'))
        except StaleElementReferenceException:
            print('Append error')
        #WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//a[@data-page='next']")))
        #next_button=driver.find_element(By.XPATH,"//a[@data-page='next']")
        #next_button.click()
   
    except NoSuchElementException:
        print('scraping done')

driver.quit()

In [197]:
len(urls)

375

In [199]:
for i in urls:  # Iterating each and every URL to fetch full details
    driver.get(i)  # Taking each URL one by one as an input
    sleep(1)

    # BHK_type 
    try:
        beds_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[1]/div[2]/span/h4')
        bed_text = beds_.text.replace('Bedroom', '').strip()
        BHK_type.append(bed_text)
    except:
        BHK_type.append('None')

    # Bathroom
    try:
        bath_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[3]/div[2]/span/h4')
        bath_text = bath_.text.replace('Bathroom', '').strip()
        bath.append(bath_text)
    except:
        bath.append('None')

    # Carpet area
    try:
        cart_area = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[6]/div[3]/h5')
        if 'Sq.Ft' in cart_area.text:
            carpet_area_ = cart_area.text.replace(' Sq.Ft', '').replace(',', '')  # Remove ' Sq.Ft' and commas
            carpet_area.append(carpet_area_)
        else:
            carpet_area.append('None')
    except:
        carpet_area.append('None')

    # Price per square feet
    try:
        PRSF = driver.find_element(By.XPATH, '//div[@class="flexbox hidden-mobile"]/div[5]/div[1]')
        price_per_square_feet.append(PRSF.text)
    except:
        price_per_square_feet.append('None')

    # Property_Type
    try:
        Pro_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[6]/div[2]/span/h4')
        property_type.append(Pro_.text)
    except:
        property_type.append('None')

    # Status
    try:
        sta = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[4]/div[2]/span/h4')
        status.append(sta.text)
    except:
        status.append('None')

    # Year Built
    try:
        Year = driver.find_element(By.XPATH, '//div[@class="outer-parameters-block"]/ul/li[10]/div[2]')
        year_text = Year.text.strip()
        
        if year_text.isdigit() and len(year_text) == 4:
            year_built.append(int(year_text))
        else:
            year_built.append('None')  # Append 'None' if not a valid year
    except:
        year_built.append('None')

    # Landmarks
    try:
        land = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[3]/div/div/span[2]/a[1]')
        landmark.append(land.text)
    except:
        landmark.append('None')

    # Balcony
    try:
        Balc = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[5]/div[2]/span/h4')
        if Balc.text.strip().upper() == 'NA':
            balcony.append('None')
        else:
            balcony.append(Balc.text.strip())
    except:
        balcony.append('None')

    # Address
    try:
        Addr = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[2]/div[1]/h5')
        address.append(Addr.text)
    except:
        address.append('None')

    # City
    try:
        city_ = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        city_text = city_.text.split(',')[0]  # Split the text by comma and get the first part
        city.append(city_text)
    except:
        city.append('Mumbai')  
    # State_code
    try:
        State_cod = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        State_code_ = State_cod.text.split(',')[1].strip()  # Split the text by comma and get the second part
        state_code.append(State_code_)
    except:
        state_code.append('MH')  # Default state code assumed as 'KA'

    # Country
    try:
        Addr = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        country.append(Addr.text)
    except:
        country.append('India')  # Default country assumed as 'India'

    # Floor
    try:
        fl = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[9]/div[3]/h5')
        if '/' in fl.text:
            floor.append(fl.text)
        else:
            floor.append('None')
    except:
        floor.append('None')

    # Transaction type
    try:
        trans = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        transaction_type.append(trans.text)
    except:
        transaction_type.append('None')

    # Furnished status
    try:
        furnish = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[7]/div[3]/h5')
        if 'Fully Furnished' in furnish.text or 'Semi' in furnish.text:
            furnished_status.append(furnish.text)
        else:
            furnished_status.append('None')
    except:
        furnished_status.append('None')

    # Facing
    try:
        fac = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[8]/div[3]/h5')
        fac_text = fac.text.lower()  # Convert text to lowercase for case insensitivity
    
        if 'north-east' in fac_text or 'northeast' in fac_text:
            facing.append('northeast')
        elif 'south-east' in fac_text or 'southeast' in fac_text:
            facing.append('southeast')
        elif 'south-west' in fac_text or 'southwest' in fac_text:
            facing.append('southwest')
        elif 'north-west' in fac_text or 'northwest' in fac_text:
            facing.append('northwest')
        elif 'north' in fac_text:
            facing.append('North')
        elif 'east' in fac_text:
            facing.append('East')
        elif 'south' in fac_text:
            facing.append('South')
        elif 'west' in fac_text:
            facing.append('West')
        else:
            facing.append('None')
    except:
        facing.append('None')

    # Car Parking
    try:
        Car_Par = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[7]/div[2]/span/h4')
        car_parking.append(Car_Par.text)
    except:
        car_parking.append('None')

    # Type of ownership
    try:
        Type_of_owners = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[2]/div[3]/h5')
        type_of_ownership.append(Type_of_owners.text)
    except:
        type_of_ownership.append('None')

    # Booking amount
    try:
        booking = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        booking_amount.append(booking.text)
    except:
        booking_amount.append('None')

    
    # Buy total price
    CRORE_TO_THOUSAND = 10000000
    LAC_TO_THOUSAND = 100000

    def convert_price_to_thousands(price_text):
        if 'Crores' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Crores', '').strip())
            price_in_thousands = price_value * CRORE_TO_THOUSAND
        elif 'Lacs' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Lacs', '').strip())
            price_in_thousands = price_value * LAC_TO_THOUSAND
        else:
            price_in_thousands = float(price_text.replace('₹', '').strip())
        return price_in_thousands

    try:
        buy_t = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[3]/div[1]/div/div[1]/span')
        price_text = buy_t.text
        price_in_thousands = convert_price_to_thousands(price_text)
        buy_total_price.append(f'{round(price_in_thousands)}') 
    except:
        buy_total_price.append('None')
    
# Quit WebDriver
driver.quit()

In [200]:
df6=pd.DataFrame({
    "BHK_type": BHK_type,
    "Beds": BHK_type,
    "Bathroom": bath,
    "Carpet_area": carpet_area,
    "Price_per_square_feet": price_per_square_feet,
    "Property_Type": property_type,
    "Status": status,
    "Year_Built": year_built,
    "Landmarks": landmark,
    "Balcony": balcony,
    "Address": address,
    "City": city,
    "State_Code": state_code,
    "Country": country,
    "Floor": floor,
    "Transaction_Type": transaction_type,
    "Furnished_Status": furnished_status,
    "Facing": facing,
    "Car_Parking": car_parking,
    "Type_of_Ownership": type_of_ownership,
    "Booking_Amount": booking_amount,
    "Buy_Total_Price": buy_total_price
})

In [201]:
df6

,BHK_type,Beds,Bathroom,Carpet_area,Price_per_square_feet,Property_Type,Status,Year_Built,Landmarks,Balcony,...,State_Code,Country,Floor,Transaction_Type,Furnished_Status,Facing,Car_Parking,Type_of_Ownership,Booking_Amount,Buy_Total_Price
0,1,1,1,425,None,Pragati Chs,Immediately,None,G7 Multiplex,1,...,MH,India,8/12,None,Fully Furnished,West,Bike and Car,Self Owned,None,13200000
1,3,3,3,1235,None,Adani Realty 10 Bkc,"Jun 30, 2024",None,G7 Multiplex,None,...,MH,India,28/29,None,None,West,Car,Self Owned,None,100000000
2,2,2,2,None,None,Sheetal,"Jul 1, 2024",None,Sardar Patel Technology Business Incubator T2,1,...,MH,India,None,None,None,None,Bike and Car,Self Owned,None,40000000
3,3,3,3,1240,None,Gurukrupa Vyom,Immediately,None,Sardar Patel Technology Business Incubator T2,None,...,MH,India,9/16,None,None,northeast,Bike and Car,Self Owned,None,77800000
4,2,2,2,860,None,Shakti Sadan Apartm...,Immediately,None,G7 Multiplex,1,...,MH,India,4/8,None,Fully Furnished,South,Bike and Car,Self Owned,None,25500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,1,1,1,409,None,Antariksh Ace,"Jan 5, 2026",None,G7 Multiplex,1,...,MH,India,9/22,None,None,East,Bike and Car,Self Owned,None,12700000
371,4,4,4,1954,None,Rustomjee Ashiana,"Feb 22, 2026",None,Sardar Patel Technology Business Incubator T2,1,...,MH,India,5/10,None,None,northeast,Bike and Car,Self Owned,None,140400000
372,4,4,4,1733,None,Ajmera Prive,"Oct 31, 2025",None,Sardar Patel Technology Business Incubator T2,None,...,MH,India,5/12,None,None,northeast,Bike and Car,Self Owned,None,103400000
373,2,2,2,794,None,Agami Codename Artc...,"Feb 12, 2026",None,G7 Multiplex,None,...,MH,India,20/22,None,None,northeast,Bike and Car,Self Owned,None,36600000
374,3,3,3,1047,None,Agami Codename Artc...,"Feb 12, 2026",None,G7 Multiplex,1,...,MH,India,15/22,None,None,northeast,Bike and Car,Self Owned,None,48100000

In [202]:
df6.to_csv('Mumbai.csv', index=False)

In [209]:
#automating chrome browser
driver=webdriver.Chrome()
driver.get("https://www.nobroker.in/")
driver.maximize_window()

In [204]:
buy_button=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[1]/div[3]/div[1]')
buy_button.click()

In [205]:
#Noida City
#WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"/html/body/section/div[1]/form/div[2]/input[1]")))

#finding and sending Noida input the search input box
first_click=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
first_click.click()
sleep(2)
#sending city name in the search box
city=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
city.send_keys('Noida')
search_button=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/button")
search_button.click()

In [206]:
# creating empty lists
s_no = []
BHK_type = []
property_type = []
beds = []
bath = []
balcony = []
address = []
city = []
state_code = []
country = []
landmark = []
carpet_area = []
status = []
floor = []
transaction_type = []
year_built = []
price_per_square_feet = []
furnished_status = []
facing = []
car_parking = []
type_of_ownership = []
booking_amount = []
buy_total_price = []

In [207]:
#collecting urls of properties
urls=[]
#for page scrolling
#for i in range(1,13):
   # print('Scraping page',i)
for _ in range(7):
    driver.execute_script("window.scrollBy(0,200)")
    try:
    #scraping urls 
        WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a")))
        try:
            for url in driver.find_elements(By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a"):
                urls.append(url.get_attribute('href'))
        except StaleElementReferenceException:
            print('Append error')
        #WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//a[@data-page='next']")))
        #next_button=driver.find_element(By.XPATH,"//a[@data-page='next']")
        #next_button.click()
   
    except NoSuchElementException:
        print('scraping done')

driver.quit()

In [208]:
len(urls)

175

In [210]:
for i in urls:  # Iterating each and every URL to fetch full details
    driver.get(i)  # Taking each URL one by one as an input
    sleep(1)

    # BHK_type 
    try:
        beds_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[1]/div[2]/span/h4')
        bed_text = beds_.text.replace('Bedroom', '').strip()
        BHK_type.append(bed_text)
    except:
        BHK_type.append('None')

    # Bathroom
    try:
        bath_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[3]/div[2]/span/h4')
        bath_text = bath_.text.replace('Bathroom', '').strip()
        bath.append(bath_text)
    except:
        bath.append('None')

    # Carpet area
    try:
        cart_area = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[6]/div[3]/h5')
        if 'Sq.Ft' in cart_area.text:
            carpet_area_ = cart_area.text.replace(' Sq.Ft', '').replace(',', '')  # Remove ' Sq.Ft' and commas
            carpet_area.append(carpet_area_)
        else:
            carpet_area.append('None')
    except:
        carpet_area.append('None')

    # Price per square feet
    try:
        PRSF = driver.find_element(By.XPATH, '//div[@class="flexbox hidden-mobile"]/div[5]/div[1]')
        price_per_square_feet.append(PRSF.text)
    except:
        price_per_square_feet.append('None')

    # Property_Type
    try:
        Pro_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[6]/div[2]/span/h4')
        property_type.append(Pro_.text)
    except:
        property_type.append('None')

    # Status
    try:
        sta = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[4]/div[2]/span/h4')
        status.append(sta.text)
    except:
        status.append('None')

    # Year Built
    try:
        Year = driver.find_element(By.XPATH, '//div[@class="outer-parameters-block"]/ul/li[10]/div[2]')
        year_text = Year.text.strip()
        
        if year_text.isdigit() and len(year_text) == 4:
            year_built.append(int(year_text))
        else:
            year_built.append('None')  # Append 'None' if not a valid year
    except:
        year_built.append('None')

    # Landmarks
    try:
        land = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[3]/div/div/span[2]/a[1]')
        landmark.append(land.text)
    except:
        landmark.append('None')

    # Balcony
    try:
        Balc = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[5]/div[2]/span/h4')
        if Balc.text.strip().upper() == 'NA':
            balcony.append('None')
        else:
            balcony.append(Balc.text.strip())
    except:
        balcony.append('None')

    # Address
    try:
        Addr = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[2]/div[1]/h5')
        address.append(Addr.text)
    except:
        address.append('None')

    # City
    try:
        city_ = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        city_text = city_.text.split(',')[0]  # Split the text by comma and get the first part
        city.append(city_text)
    except:
        city.append('Noida')  
    # State_code
    try:
        State_cod = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        State_code_ = State_cod.text.split(',')[1].strip()  # Split the text by comma and get the second part
        state_code.append(State_code_)
    except:
        state_code.append('UP')  # Default state code assumed as 'KA'

    # Country
    try:
        Addr = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        country.append(Addr.text)
    except:
        country.append('India')  # Default country assumed as 'India'

    # Floor
    try:
        fl = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[9]/div[3]/h5')
        if '/' in fl.text:
            floor.append(fl.text)
        else:
            floor.append('None')
    except:
        floor.append('None')

    # Transaction type
    try:
        trans = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        transaction_type.append(trans.text)
    except:
        transaction_type.append('None')

    # Furnished status
    try:
        furnish = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[7]/div[3]/h5')
        if 'Fully Furnished' in furnish.text or 'Semi' in furnish.text:
            furnished_status.append(furnish.text)
        else:
            furnished_status.append('None')
    except:
        furnished_status.append('None')

    # Facing
    try:
        fac = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[8]/div[3]/h5')
        fac_text = fac.text.lower()  # Convert text to lowercase for case insensitivity
    
        if 'north-east' in fac_text or 'northeast' in fac_text:
            facing.append('northeast')
        elif 'south-east' in fac_text or 'southeast' in fac_text:
            facing.append('southeast')
        elif 'south-west' in fac_text or 'southwest' in fac_text:
            facing.append('southwest')
        elif 'north-west' in fac_text or 'northwest' in fac_text:
            facing.append('northwest')
        elif 'north' in fac_text:
            facing.append('North')
        elif 'east' in fac_text:
            facing.append('East')
        elif 'south' in fac_text:
            facing.append('South')
        elif 'west' in fac_text:
            facing.append('West')
        else:
            facing.append('None')
    except:
        facing.append('None')

    # Car Parking
    try:
        Car_Par = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[7]/div[2]/span/h4')
        car_parking.append(Car_Par.text)
    except:
        car_parking.append('None')

    # Type of ownership
    try:
        Type_of_owners = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[2]/div[3]/h5')
        type_of_ownership.append(Type_of_owners.text)
    except:
        type_of_ownership.append('None')

    # Booking amount
    try:
        booking = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        booking_amount.append(booking.text)
    except:
        booking_amount.append('None')

    
    # Buy total price
    CRORE_TO_THOUSAND = 10000000
    LAC_TO_THOUSAND = 100000

    def convert_price_to_thousands(price_text):
        if 'Crores' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Crores', '').strip())
            price_in_thousands = price_value * CRORE_TO_THOUSAND
        elif 'Lacs' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Lacs', '').strip())
            price_in_thousands = price_value * LAC_TO_THOUSAND
        else:
            price_in_thousands = float(price_text.replace('₹', '').strip())
        return price_in_thousands

    try:
        buy_t = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[3]/div[1]/div/div[1]/span')
        price_text = buy_t.text
        price_in_thousands = convert_price_to_thousands(price_text)
        buy_total_price.append(f'{round(price_in_thousands)}') 
    except:
        buy_total_price.append('None')
    
# Quit WebDriver
driver.quit()

In [211]:
df7=pd.DataFrame({
    "BHK_type": BHK_type,
    "Beds": BHK_type,
    "Bathroom": bath,
    "Carpet_area": carpet_area,
    "Price_per_square_feet": price_per_square_feet,
    "Property_Type": property_type,
    "Status": status,
    "Year_Built": year_built,
    "Landmarks": landmark,
    "Balcony": balcony,
    "Address": address,
    "City": city,
    "State_Code": state_code,
    "Country": country,
    "Floor": floor,
    "Transaction_Type": transaction_type,
    "Furnished_Status": furnished_status,
    "Facing": facing,
    "Car_Parking": car_parking,
    "Type_of_Ownership": type_of_ownership,
    "Booking_Amount": booking_amount,
    "Buy_Total_Price": buy_total_price
})

In [212]:
df7

,BHK_type,Beds,Bathroom,Carpet_area,Price_per_square_feet,Property_Type,Status,Year_Built,Landmarks,Balcony,...,State_Code,Country,Floor,Transaction_Type,Furnished_Status,Facing,Car_Parking,Type_of_Ownership,Booking_Amount,Buy_Total_Price
0,4,4,4,2644,None,"Gulshan Vivante, Se...",Immediately,None,Sandal Suites Operated By Lemon Tree Hotels,5,...,UP,India,9/20,None,Semi,East,Car,Self Owned,None,34700000
1,3,3,3,None,None,Lowrise Tower,"Aug 1, 2024",None,Sandal Suites Operated By Lemon Tree Hotels,4,...,UP,India,None,None,None,None,Bike and Car,Self Owned,None,16000000
2,2,2,2,None,None,Paramount Floraville,Immediately,None,Sandal Suites Operated By Lemon Tree Hotels,3,...,UP,India,None,None,None,None,Car,Self Owned,None,11300000
3,2,2,2,None,None,Paramount Floraville,Immediately,None,Sandal Suites Operated By Lemon Tree Hotels,None,...,UP,India,None,None,None,None,Bike and Car,Self Owned,None,None
4,2,2,2,None,None,Paramount Floraville,"Jul 1, 2024",None,Sandal Suites Operated By Lemon Tree Hotels,None,...,UP,India,None,None,None,None,Bike and Car,Self Owned,None,11000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,3,3,4,None,None,Purvanchal Royal Pa...,Immediately,None,McDonald'S India,3,...,UP,India,None,None,None,None,Car,Self Owned,None,25000000
171,4,4,4,None,None,Purvanchal Royal Pa...,Immediately,None,McDonald'S India,3,...,UP,India,None,None,None,None,Car,Self Owned,None,43000000
172,3,3,2,None,None,Purvanchal Royal Pa...,Immediately,None,Noida Sector 137,None,...,UP,India,None,None,None,None,Bike and Car,Self Owned,None,15000000
173,3,3,2,None,None,Purvanchal Royal Pa...,"Jun 29, 2024",None,McDonald'S India,2,...,UP,India,None,None,None,None,Bike and Car,Self Owned,None,14500000
174,2,2,2,None,None,Ajnara Daffodil,Immediately,None,Sandal Suites Operated By Lemon Tree Hotels,3,...,UP,India,None,None,None,None,Bike and Car,Self Owned,None,11000000

In [213]:
df7.to_csv('Noida.csv', index=False)

In [220]:
#automating chrome browser
driver=webdriver.Chrome()
driver.get("https://www.nobroker.in/")
driver.maximize_window()

In [215]:
buy_button=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[1]/div[3]/div[1]')
buy_button.click()

In [216]:
#Ghaziabad City
#WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"/html/body/section/div[1]/form/div[2]/input[1]")))

#finding and sending Noida input the search input box
first_click=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
first_click.click()
sleep(2)
#sending city name in the search box
city=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
city.send_keys('ghaziabad')
search_button=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/button")
search_button.click()

In [217]:
# creating empty lists
s_no = []
BHK_type = []
property_type = []
beds = []
bath = []
balcony = []
address = []
city = []
state_code = []
country = []
landmark = []
carpet_area = []
status = []
floor = []
transaction_type = []
year_built = []
price_per_square_feet = []
furnished_status = []
facing = []
car_parking = []
type_of_ownership = []
booking_amount = []
buy_total_price = []

In [218]:
#collecting urls of properties
urls=[]
#for page scrolling
#for i in range(1,13):
   # print('Scraping page',i)
for _ in range(7):
    driver.execute_script("window.scrollBy(0,200)")
    try:
    #scraping urls 
        WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a")))
        try:
            for url in driver.find_elements(By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a"):
                urls.append(url.get_attribute('href'))
        except StaleElementReferenceException:
            print('Append error')
        #WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//a[@data-page='next']")))
        #next_button=driver.find_element(By.XPATH,"//a[@data-page='next']")
        #next_button.click()
   
    except NoSuchElementException:
        print('scraping done')

driver.quit()

In [219]:
len(urls)

175

In [221]:
for i in urls:  # Iterating each and every URL to fetch full details
    driver.get(i)  # Taking each URL one by one as an input
    sleep(1)

    # BHK_type 
    try:
        beds_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[1]/div[2]/span/h4')
        bed_text = beds_.text.replace('Bedroom', '').strip()
        BHK_type.append(bed_text)
    except:
        BHK_type.append('None')

    # Bathroom
    try:
        bath_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[3]/div[2]/span/h4')
        bath_text = bath_.text.replace('Bathroom', '').strip()
        bath.append(bath_text)
    except:
        bath.append('None')

    # Carpet area
    try:
        cart_area = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[6]/div[3]/h5')
        if 'Sq.Ft' in cart_area.text:
            carpet_area_ = cart_area.text.replace(' Sq.Ft', '').replace(',', '')  # Remove ' Sq.Ft' and commas
            carpet_area.append(carpet_area_)
        else:
            carpet_area.append('None')
    except:
        carpet_area.append('None')

    # Price per square feet
    try:
        PRSF = driver.find_element(By.XPATH, '//div[@class="flexbox hidden-mobile"]/div[5]/div[1]')
        price_per_square_feet.append(PRSF.text)
    except:
        price_per_square_feet.append('None')

    # Property_Type
    try:
        Pro_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[6]/div[2]/span/h4')
        property_type.append(Pro_.text)
    except:
        property_type.append('None')

    # Status
    try:
        sta = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[4]/div[2]/span/h4')
        status.append(sta.text)
    except:
        status.append('None')

    # Year Built
    try:
        Year = driver.find_element(By.XPATH, '//div[@class="outer-parameters-block"]/ul/li[10]/div[2]')
        year_text = Year.text.strip()
        
        if year_text.isdigit() and len(year_text) == 4:
            year_built.append(int(year_text))
        else:
            year_built.append('None')  # Append 'None' if not a valid year
    except:
        year_built.append('None')

    # Landmarks
    try:
        land = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[3]/div/div/span[2]/a[1]')
        landmark.append(land.text)
    except:
        landmark.append('None')

    # Balcony
    try:
        Balc = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[5]/div[2]/span/h4')
        if Balc.text.strip().upper() == 'NA':
            balcony.append('None')
        else:
            balcony.append(Balc.text.strip())
    except:
        balcony.append('None')

    # Address
    try:
        Addr = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[2]/div[1]/h5')
        address.append(Addr.text)
    except:
        address.append('None')

    # City
    try:
        city_ = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        city_text = city_.text.split(',')[0]  # Split the text by comma and get the first part
        city.append(city_text)
    except:
        city.append('Ghaziabad')  
    # State_code
    try:
        State_cod = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        State_code_ = State_cod.text.split(',')[1].strip()  # Split the text by comma and get the second part
        state_code.append(State_code_)
    except:
        state_code.append('UP')  # Default state code assumed as 'KA'

    # Country
    try:
        Addr = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        country.append(Addr.text)
    except:
        country.append('India')  # Default country assumed as 'India'

    # Floor
    try:
        fl = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[9]/div[3]/h5')
        if '/' in fl.text:
            floor.append(fl.text)
        else:
            floor.append('None')
    except:
        floor.append('None')

    # Transaction type
    try:
        trans = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        transaction_type.append(trans.text)
    except:
        transaction_type.append('None')

    # Furnished status
    try:
        furnish = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[7]/div[3]/h5')
        if 'Fully Furnished' in furnish.text or 'Semi' in furnish.text:
            furnished_status.append(furnish.text)
        else:
            furnished_status.append('None')
    except:
        furnished_status.append('None')

    # Facing
    try:
        fac = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[8]/div[3]/h5')
        fac_text = fac.text.lower()  # Convert text to lowercase for case insensitivity
    
        if 'north-east' in fac_text or 'northeast' in fac_text:
            facing.append('northeast')
        elif 'south-east' in fac_text or 'southeast' in fac_text:
            facing.append('southeast')
        elif 'south-west' in fac_text or 'southwest' in fac_text:
            facing.append('southwest')
        elif 'north-west' in fac_text or 'northwest' in fac_text:
            facing.append('northwest')
        elif 'north' in fac_text:
            facing.append('North')
        elif 'east' in fac_text:
            facing.append('East')
        elif 'south' in fac_text:
            facing.append('South')
        elif 'west' in fac_text:
            facing.append('West')
        else:
            facing.append('None')
    except:
        facing.append('None')

    # Car Parking
    try:
        Car_Par = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[7]/div[2]/span/h4')
        car_parking.append(Car_Par.text)
    except:
        car_parking.append('None')

    # Type of ownership
    try:
        Type_of_owners = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[2]/div[3]/h5')
        type_of_ownership.append(Type_of_owners.text)
    except:
        type_of_ownership.append('None')

    # Booking amount
    try:
        booking = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        booking_amount.append(booking.text)
    except:
        booking_amount.append('None')

    
    # Buy total price
    CRORE_TO_THOUSAND = 10000000
    LAC_TO_THOUSAND = 100000

    def convert_price_to_thousands(price_text):
        if 'Crores' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Crores', '').strip())
            price_in_thousands = price_value * CRORE_TO_THOUSAND
        elif 'Lacs' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Lacs', '').strip())
            price_in_thousands = price_value * LAC_TO_THOUSAND
        else:
            price_in_thousands = float(price_text.replace('₹', '').strip())
        return price_in_thousands

    try:
        buy_t = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[3]/div[1]/div/div[1]/span')
        price_text = buy_t.text
        price_in_thousands = convert_price_to_thousands(price_text)
        buy_total_price.append(f'{round(price_in_thousands)}') 
    except:
        buy_total_price.append('None')
    
# Quit WebDriver
driver.quit()

In [222]:
df8=pd.DataFrame({
    "BHK_type": BHK_type,
    "Beds": BHK_type,
    "Bathroom": bath,
    "Carpet_area": carpet_area,
    "Price_per_square_feet": price_per_square_feet,
    "Property_Type": property_type,
    "Status": status,
    "Year_Built": year_built,
    "Landmarks": landmark,
    "Balcony": balcony,
    "Address": address,
    "City": city,
    "State_Code": state_code,
    "Country": country,
    "Floor": floor,
    "Transaction_Type": transaction_type,
    "Furnished_Status": furnished_status,
    "Facing": facing,
    "Car_Parking": car_parking,
    "Type_of_Ownership": type_of_ownership,
    "Booking_Amount": booking_amount,
    "Buy_Total_Price": buy_total_price
})

In [223]:
df8

,BHK_type,Beds,Bathroom,Carpet_area,Price_per_square_feet,Property_Type,Status,Year_Built,Landmarks,Balcony,...,State_Code,Country,Floor,Transaction_Type,Furnished_Status,Facing,Car_Parking,Type_of_Ownership,Booking_Amount,Buy_Total_Price
0,1,1,1,None,None,Standalone Building,Immediately,None,Movie Magic Cinema,1,...,UP,India,None,None,None,None,Bike,Self Owned,None,1290000
1,2,2,1,None,None,Gda Flats,Immediately,None,Gaur Central Mall,1,...,UP,India,None,None,None,None,None,Self Owned,None,2500000
2,2,2,2,900,None,"Sai Enclave Plot, N...",Immediately,None,Gaur Central Mall,1,...,UP,India,1/2,None,Semi,East,Car,Self Owned,None,3500000
3,2,2,2,None,None,Independent House,Immediately,None,Gaur Central Mall,1,...,UP,India,None,None,None,None,None,Self Owned,None,2600000
4,1,1,1,None,None,Independent House,Immediately,None,Gaur Central Mall,None,...,UP,India,1/1,None,None,West,None,Self Owned,None,700000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,2,2,2,None,None,Gh-7,Immediately,None,VVIP Style,3,...,UP,India,None,None,None,None,Bike and Car,Self Owned,None,7500000
171,1,1,1,None,None,Apartment,Immediately,None,Gaur Central Mall,None,...,UP,India,None,None,None,None,None,Self Owned,None,1600000
172,3,3,4,None,None,Standalone Building,Immediately,None,Gaur Central Mall,1,...,UP,India,None,None,None,None,None,Self Owned,None,3700000
173,2,2,2,None,None,Apartment,Immediately,None,Gaur Central Mall,None,...,UP,India,None,None,None,None,Bike and Car,Self Owned,None,2000000
174,4,4,6,None,None,Standalone Building,Immediately,None,Gaur Central Mall,None,...,UP,India,None,None,None,None,Bike and Car,Self Owned,None,40000000

In [224]:
df8.to_csv('Ghaziabad.csv', index=False)

In [231]:
#automating chrome browser
driver=webdriver.Chrome()
driver.get("https://www.nobroker.in/")
driver.maximize_window()

In [226]:
buy_button=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[1]/div[3]/div[1]')
buy_button.click()

In [227]:
#Faridabad City
#WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"/html/body/section/div[1]/form/div[2]/input[1]")))

#finding and sending Noida input the search input box
first_click=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
first_click.click()
sleep(2)
#sending city name in the search box
city=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
city.send_keys('Faridabad')
search_button=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/button")
search_button.click()

In [228]:
# creating empty lists
s_no = []
BHK_type = []
property_type = []
beds = []
bath = []
balcony = []
address = []
city = []
state_code = []
country = []
landmark = []
carpet_area = []
status = []
floor = []
transaction_type = []
year_built = []
price_per_square_feet = []
furnished_status = []
facing = []
car_parking = []
type_of_ownership = []
booking_amount = []
buy_total_price = []

In [229]:
#collecting urls of properties
urls=[]
#for page scrolling
#for i in range(1,13):
   # print('Scraping page',i)
for _ in range(6):
    driver.execute_script("window.scrollBy(0,200)")
    try:
    #scraping urls 
        WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a")))
        try:
            for url in driver.find_elements(By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a"):
                urls.append(url.get_attribute('href'))
        except StaleElementReferenceException:
            print('Append error')
        #WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//a[@data-page='next']")))
        #next_button=driver.find_element(By.XPATH,"//a[@data-page='next']")
        #next_button.click()
   
    except NoSuchElementException:
        print('scraping done')

driver.quit()

In [230]:
len(urls)

150

In [232]:
for i in urls:  # Iterating each and every URL to fetch full details
    driver.get(i)  # Taking each URL one by one as an input
    sleep(1)

    # BHK_type 
    try:
        beds_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[1]/div[2]/span/h4')
        bed_text = beds_.text.replace('Bedroom', '').strip()
        BHK_type.append(bed_text)
    except:
        BHK_type.append('None')

    # Bathroom
    try:
        bath_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[3]/div[2]/span/h4')
        bath_text = bath_.text.replace('Bathroom', '').strip()
        bath.append(bath_text)
    except:
        bath.append('None')

    # Carpet area
    try:
        cart_area = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[6]/div[3]/h5')
        if 'Sq.Ft' in cart_area.text:
            carpet_area_ = cart_area.text.replace(' Sq.Ft', '').replace(',', '')  # Remove ' Sq.Ft' and commas
            carpet_area.append(carpet_area_)
        else:
            carpet_area.append('None')
    except:
        carpet_area.append('None')

    # Price per square feet
    try:
        PRSF = driver.find_element(By.XPATH, '//div[@class="flexbox hidden-mobile"]/div[5]/div[1]')
        price_per_square_feet.append(PRSF.text)
    except:
        price_per_square_feet.append('None')

    # Property_Type
    try:
        Pro_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[6]/div[2]/span/h4')
        property_type.append(Pro_.text)
    except:
        property_type.append('None')

    # Status
    try:
        sta = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[4]/div[2]/span/h4')
        status.append(sta.text)
    except:
        status.append('None')

    # Year Built
    try:
        Year = driver.find_element(By.XPATH, '//div[@class="outer-parameters-block"]/ul/li[10]/div[2]')
        year_text = Year.text.strip()
        
        if year_text.isdigit() and len(year_text) == 4:
            year_built.append(int(year_text))
        else:
            year_built.append('None')  # Append 'None' if not a valid year
    except:
        year_built.append('None')

    # Landmarks
    try:
        land = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[3]/div/div/span[2]/a[1]')
        landmark.append(land.text)
    except:
        landmark.append('None')

    # Balcony
    try:
        Balc = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[5]/div[2]/span/h4')
        if Balc.text.strip().upper() == 'NA':
            balcony.append('None')
        else:
            balcony.append(Balc.text.strip())
    except:
        balcony.append('None')

    # Address
    try:
        Addr = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[2]/div[1]/h5')
        address.append(Addr.text)
    except:
        address.append('None')

    # City
    try:
        city_ = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        city_text = city_.text.split(',')[0]  # Split the text by comma and get the first part
        city.append(city_text)
    except:
        city.append('Faridabad')  
    # State_code
    try:
        State_cod = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        State_code_ = State_cod.text.split(',')[1].strip()  # Split the text by comma and get the second part
        state_code.append(State_code_)
    except:
        state_code.append('HR')  # Default state code assumed as 'KA'

    # Country
    try:
        Addr = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        country.append(Addr.text)
    except:
        country.append('India')  # Default country assumed as 'India'

    # Floor
    try:
        fl = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[9]/div[3]/h5')
        if '/' in fl.text:
            floor.append(fl.text)
        else:
            floor.append('None')
    except:
        floor.append('None')

    # Transaction type
    try:
        trans = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        transaction_type.append(trans.text)
    except:
        transaction_type.append('None')

    # Furnished status
    try:
        furnish = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[7]/div[3]/h5')
        if 'Fully Furnished' in furnish.text or 'Semi' in furnish.text:
            furnished_status.append(furnish.text)
        else:
            furnished_status.append('None')
    except:
        furnished_status.append('None')

    # Facing
    try:
        fac = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[8]/div[3]/h5')
        fac_text = fac.text.lower()  # Convert text to lowercase for case insensitivity
    
        if 'north-east' in fac_text or 'northeast' in fac_text:
            facing.append('northeast')
        elif 'south-east' in fac_text or 'southeast' in fac_text:
            facing.append('southeast')
        elif 'south-west' in fac_text or 'southwest' in fac_text:
            facing.append('southwest')
        elif 'north-west' in fac_text or 'northwest' in fac_text:
            facing.append('northwest')
        elif 'north' in fac_text:
            facing.append('North')
        elif 'east' in fac_text:
            facing.append('East')
        elif 'south' in fac_text:
            facing.append('South')
        elif 'west' in fac_text:
            facing.append('West')
        else:
            facing.append('None')
    except:
        facing.append('None')

    # Car Parking
    try:
        Car_Par = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[7]/div[2]/span/h4')
        car_parking.append(Car_Par.text)
    except:
        car_parking.append('None')

    # Type of ownership
    try:
        Type_of_owners = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[2]/div[3]/h5')
        type_of_ownership.append(Type_of_owners.text)
    except:
        type_of_ownership.append('None')

    # Booking amount
    try:
        booking = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        booking_amount.append(booking.text)
    except:
        booking_amount.append('None')

    
    # Buy total price
    CRORE_TO_THOUSAND = 10000000
    LAC_TO_THOUSAND = 100000

    def convert_price_to_thousands(price_text):
        if 'Crores' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Crores', '').strip())
            price_in_thousands = price_value * CRORE_TO_THOUSAND
        elif 'Lacs' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Lacs', '').strip())
            price_in_thousands = price_value * LAC_TO_THOUSAND
        else:
            price_in_thousands = float(price_text.replace('₹', '').strip())
        return price_in_thousands

    try:
        buy_t = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[3]/div[1]/div/div[1]/span')
        price_text = buy_t.text
        price_in_thousands = convert_price_to_thousands(price_text)
        buy_total_price.append(f'{round(price_in_thousands)}') 
    except:
        buy_total_price.append('None')
    
# Quit WebDriver
driver.quit()

In [233]:
df9=pd.DataFrame({
    "BHK_type": BHK_type,
    "Beds": BHK_type,
    "Bathroom": bath,
    "Carpet_area": carpet_area,
    "Price_per_square_feet": price_per_square_feet,
    "Property_Type": property_type,
    "Status": status,
    "Year_Built": year_built,
    "Landmarks": landmark,
    "Balcony": balcony,
    "Address": address,
    "City": city,
    "State_Code": state_code,
    "Country": country,
    "Floor": floor,
    "Transaction_Type": transaction_type,
    "Furnished_Status": furnished_status,
    "Facing": facing,
    "Car_Parking": car_parking,
    "Type_of_Ownership": type_of_ownership,
    "Booking_Amount": booking_amount,
    "Buy_Total_Price": buy_total_price
})

In [234]:
df9

,BHK_type,Beds,Bathroom,Carpet_area,Price_per_square_feet,Property_Type,Status,Year_Built,Landmarks,Balcony,...,State_Code,Country,Floor,Transaction_Type,Furnished_Status,Facing,Car_Parking,Type_of_Ownership,Booking_Amount,Buy_Total_Price
0,2,2,1,None,None,Independent House,Immediately,None,Crown Plaza,None,...,HR,India,None,None,None,None,None,Self Owned,None,4800000
1,4,4,4,None,None,Independent House,Immediately,None,Crown Plaza,None,...,HR,India,None,None,None,None,Bike and Car,Self Owned,None,26000000
2,2,2,2,None,None,Independent House,Immediately,None,Crown Plaza,None,...,HR,India,None,None,None,None,Bike,Self Owned,None,15000000
3,2,2,2,None,None,Apartment,Immediately,None,Crown Plaza,1,...,HR,India,None,None,None,None,Bike,Self Owned,None,3700000
4,1,1,1,None,None,Independent House,Immediately,None,INOX EF3 Cinema,None,...,HR,India,None,None,None,None,Bike,Self Owned,None,2200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,3,3,2,None,None,Standalone Building,Immediately,None,Crown Plaza,None,...,HR,India,None,None,None,None,Bike and Car,Self Owned,None,7000000
146,4,4,4,None,None,Independent House,Immediately,None,Crown Plaza,None,...,HR,India,None,None,None,None,Bike and Car,Self Owned,None,7000000
147,3,3,2,None,None,Standalone Building,Immediately,None,Crown Plaza,None,...,HR,India,None,None,None,None,Bike and Car,Self Owned,None,13500000
148,4,4,4,None,None,Standalone Building,Immediately,None,Crown Plaza,None,...,HR,India,None,None,None,None,Bike and Car,Self Owned,None,26000000
149,3,3,3,None,None,Independent House,Immediately,None,INOX EF3 Cinema,None,...,HR,India,None,None,None,None,None,Self Owned,None,11000000

In [235]:
df9.to_csv('Faridabad.csv', index=False)

In [65]:
#automating chrome browser
driver=webdriver.Chrome()
driver.get("https://www.nobroker.in/")
driver.maximize_window()

In [49]:
buy_button=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[1]/div[3]/div[1]')
buy_button.click()

In [50]:
#Greater Noida City
#WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"/html/body/section/div[1]/form/div[2]/input[1]")))

#finding and sending Noida input the search input box
first_click=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
first_click.click()
sleep(2)
#sending city name in the search box
city=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/div[2]/div/div/input")
city.send_keys('Sector 1')
search_button=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[4]/button")
search_button.click()

In [51]:
# creating empty lists
s_no = []
BHK_type = []
property_type = []
beds = []
bath = []
balcony = []
address = []
city = []
state_code = []
country = []
landmark = []
carpet_area = []
status = []
floor = []
transaction_type = []
year_built = []
price_per_square_feet = []
furnished_status = []
facing = []
car_parking = []
type_of_ownership = []
booking_amount = []
buy_total_price = []

In [63]:
#collecting urls of properties
urls=[]
#for page scrolling
#for i in range(1,13):
   # print('Scraping page',i)
for _ in range(17):
    driver.execute_script("window.scrollBy(0,270)")
    try:
    #scraping urls 
        WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a")))
        try:
            for url in driver.find_elements(By.XPATH,"//h2[@class='heading-6 flex items-center font-semi-bold m-0']/a"):
                urls.append(url.get_attribute('href'))
        except StaleElementReferenceException:
            print('Append error')
        #WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//a[@data-page='next']")))
        #next_button=driver.find_element(By.XPATH,"//a[@data-page='next']")
        #next_button.click()
   
    except NoSuchElementException:
        print('scraping done')

driver.quit()

In [64]:
len(urls)

425

In [66]:
for i in urls:  # Iterating each and every URL to fetch full details
    driver.get(i)  # Taking each URL one by one as an input
    sleep(1)

    # BHK_type 
    try:
        beds_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[1]/div[2]/span/h4')
        bed_text = beds_.text.replace('Bedroom', '').strip()
        BHK_type.append(bed_text)
    except:
        BHK_type.append('None')

    # Bathroom
    try:
        bath_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[3]/div[2]/span/h4')
        bath_text = bath_.text.replace('Bathroom', '').strip()
        bath.append(bath_text)
    except:
        bath.append('None')

    # Carpet area
    try:
        cart_area = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[6]/div[3]/h5')
        if 'Sq.Ft' in cart_area.text:
            carpet_area_ = cart_area.text.replace(' Sq.Ft', '').replace(',', '')  # Remove ' Sq.Ft' and commas
            carpet_area.append(carpet_area_)
        else:
            carpet_area.append('None')
    except:
        carpet_area.append('None')

    # Price per square feet
    try:
        PRSF = driver.find_element(By.XPATH, '//div[@class="flexbox hidden-mobile"]/div[5]/div[1]')
        price_per_square_feet.append(PRSF.text)
    except:
        price_per_square_feet.append('None')

    # Property_Type
    try:
        Pro_ = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[6]/div[2]/span/h4')
        property_type.append(Pro_.text)
    except:
        property_type.append('None')

    # Status
    try:
        sta = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[4]/div[2]/span/h4')
        status.append(sta.text)
    except:
        status.append('None')

    # Year Built
    try:
        Year = driver.find_element(By.XPATH, '//div[@class="outer-parameters-block"]/ul/li[10]/div[2]')
        year_text = Year.text.strip()
        
        if year_text.isdigit() and len(year_text) == 4:
            year_built.append(int(year_text))
        else:
            year_built.append('None')  # Append 'None' if not a valid year
    except:
        year_built.append('None')

    # Landmarks
    try:
        land = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[3]/div/div/span[2]/a[1]')
        landmark.append(land.text)
    except:
        landmark.append('None')

    # Balcony
    try:
        Balc = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[5]/div[2]/span/h4')
        if Balc.text.strip().upper() == 'NA':
            balcony.append('None')
        else:
            balcony.append(Balc.text.strip())
    except:
        balcony.append('None')

    # Address
    try:
        Addr = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[2]/div[1]/h5')
        address.append(Addr.text)
    except:
        address.append('None')

    # City
    try:
        city_ = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        city_text = city_.text.split(',')[0]  # Split the text by comma and get the first part
        city.append(city_text)
    except:
        city.append('Greater Noida')  
    # State_code
    try:
        State_cod = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        State_code_ = State_cod.text.split(',')[1].strip()  # Split the text by comma and get the second part
        state_code.append(State_code_)
    except:
        state_code.append('UP')  # Default state code assumed as 'KA'

    # Country
    try:
        Addr = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        country.append(Addr.text)
    except:
        country.append('India')  # Default country assumed as 'India'

    # Floor
    try:
        fl = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[9]/div[3]/h5')
        if '/' in fl.text:
            floor.append(fl.text)
        else:
            floor.append('None')
    except:
        floor.append('None')

    # Transaction type
    try:
        trans = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        transaction_type.append(trans.text)
    except:
        transaction_type.append('None')

    # Furnished status
    try:
        furnish = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[7]/div[3]/h5')
        if 'Fully Furnished' in furnish.text or 'Semi' in furnish.text:
            furnished_status.append(furnish.text)
        else:
            furnished_status.append('None')
    except:
        furnished_status.append('None')

    # Facing
    try:
        fac = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[8]/div[3]/h5')
        fac_text = fac.text.lower()  # Convert text to lowercase for case insensitivity
    
        if 'north-east' in fac_text or 'northeast' in fac_text:
            facing.append('northeast')
        elif 'south-east' in fac_text or 'southeast' in fac_text:
            facing.append('southeast')
        elif 'south-west' in fac_text or 'southwest' in fac_text:
            facing.append('southwest')
        elif 'north-west' in fac_text or 'northwest' in fac_text:
            facing.append('northwest')
        elif 'north' in fac_text:
            facing.append('North')
        elif 'east' in fac_text:
            facing.append('East')
        elif 'south' in fac_text:
            facing.append('South')
        elif 'west' in fac_text:
            facing.append('West')
        else:
            facing.append('None')
    except:
        facing.append('None')

    # Car Parking
    try:
        Car_Par = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[2]/div[2]/div/section/div[2]/div[7]/div[2]/span/h4')
        car_parking.append(Car_Par.text)
    except:
        car_parking.append('None')

    # Type of ownership
    try:
        Type_of_owners = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[2]/div/div[1]/div[1]/div/div[2]/div[2]/div[3]/h5')
        type_of_ownership.append(Type_of_owners.text)
    except:
        type_of_ownership.append('None')

    # Booking amount
    try:
        booking = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        booking_amount.append(booking.text)
    except:
        booking_amount.append('None')

    
    # Buy total price
    CRORE_TO_THOUSAND = 10000000
    LAC_TO_THOUSAND = 100000

    def convert_price_to_thousands(price_text):
        if 'Crores' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Crores', '').strip())
            price_in_thousands = price_value * CRORE_TO_THOUSAND
        elif 'Lacs' in price_text:
            price_value = float(price_text.replace('₹', '').replace('Lacs', '').strip())
            price_in_thousands = price_value * LAC_TO_THOUSAND
        else:
            price_in_thousands = float(price_text.replace('₹', '').strip())
        return price_in_thousands

    try:
        buy_t = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/section/div/div[1]/div/div/section[1]/div/div[1]/div/div/div[1]/div[3]/div[1]/div/div[1]/span')
        price_text = buy_t.text
        price_in_thousands = convert_price_to_thousands(price_text)
        buy_total_price.append(f'{round(price_in_thousands)}') 
    except:
        buy_total_price.append('None')
    
# Quit WebDriver
driver.quit()

In [67]:
df10=pd.DataFrame({
    "BHK_type": BHK_type,
    "Beds": BHK_type,
    "Bathroom": bath,
    "Carpet_area": carpet_area,
    "Price_per_square_feet": price_per_square_feet,
    "Property_Type": property_type,
    "Status": status,
    "Year_Built": year_built,
    "Landmarks": landmark,
    "Balcony": balcony,
    "Address": address,
    "City": city,
    "State_Code": state_code,
    "Country": country,
    "Floor": floor,
    "Transaction_Type": transaction_type,
    "Furnished_Status": furnished_status,
    "Facing": facing,
    "Car_Parking": car_parking,
    "Type_of_Ownership": type_of_ownership,
    "Booking_Amount": booking_amount,
    "Buy_Total_Price": buy_total_price
})

In [68]:
df10

,BHK_type,Beds,Bathroom,Carpet_area,Price_per_square_feet,Property_Type,Status,Year_Built,Landmarks,Balcony,...,State_Code,Country,Floor,Transaction_Type,Furnished_Status,Facing,Car_Parking,Type_of_Ownership,Booking_Amount,Buy_Total_Price
0,2,2,2,900,None,Krystal Supremus,Immediately,None,BADAMI'S SWEETS AND RESTAURANT,1,...,UP,India,2/4,None,Semi,northeast,Car,Self Owned,None,3200000
1,2,2,2,800,None,Krystal Floor,Immediately,None,BADAMI'S SWEETS AND RESTAURANT,1,...,UP,India,2/4,None,Semi,northeast,Car,Self Owned,None,3200000
2,4,4,4,1126,None,"Ace Divino, Sector 1",Immediately,None,BADAMI'S SWEETS AND RESTAURANT,4,...,UP,India,10/18,None,Semi,northeast,Car,Self Owned,None,19500000
3,2,2,2,None,None,Irish Pearls,Immediately,None,BADAMI'S SWEETS AND RESTAURANT,4,...,UP,India,None,None,None,None,Bike and Car,On Lease 99 Years,None,7800000
4,2,2,2,900,None,Royal Residency,Immediately,None,BADAMI'S SWEETS AND RESTAURANT,1,...,UP,India,2/4,None,Semi,northeast,Car,Self Owned,None,3500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,3,3,2,1100,None,Ace Divino,Immediately,None,BADAMI'S SWEETS AND RESTAURANT,3,...,UP,India,12/26,None,None,East,Bike and Car,Self Owned,None,15600000
421,3,3,2,None,None,Panchsheel Hynish,Immediately,None,BADAMI'S SWEETS AND RESTAURANT,None,...,UP,India,None,None,None,None,Bike and Car,Self Owned,None,4500000
422,2,2,2,None,None,Ace City,Immediately,None,BADAMI'S SWEETS AND RESTAURANT,2,...,UP,India,None,None,None,None,Car,Self Owned,None,8500000
423,2,2,2,800,None,Twin Celestial,Immediately,None,BADAMI'S SWEETS AND RESTAURANT,2,...,UP,India,0/4,None,Semi,northeast,Bike and Car,Self Owned,None,2700000
424,3,3,3,None,None,Ace Divino,Immediately,None,BADAMI'S SWEETS AND RESTAURANT,2,...,UP,India,None,None,None,None,Car,Self Owned,None,16500000

In [69]:
df10.to_csv('Greater_Noida.csv', index=False)

In [44]:
#automating chrome browser
driver=webdriver.Chrome()
driver.get("https://vestapreferred.com/")
driver.maximize_window()

In [21]:
buy_button=driver.find_element(By.XPATH,'/html/body/main/header/div/div[1]/div/ul/li[1]/a')
buy_button.click()

In [39]:
# creating empty lists
s_no = []
BHK_type = []
property_type = []
beds = []
bath = []
balcony = []
address = []
city = []
state_code = []
country = []
landmark = []
carpet_area = []
status = []
floor = []
transaction_type = []
year_built = []
price_per_square_feet = []
furnished_status = []
facing = []
car_parking = []
type_of_ownership = []
booking_amount = []
buy_total_price = []

In [34]:
#collecting urls of properties
urls=[]
#for page scrolling
#for i in range(1,13):
   # print('Scraping page',i)
for _ in range(8):
    driver.execute_script("window.scrollBy(0,300)")
    try:
    #scraping urls 
        WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,'//div[@itemtype="http://schema.org/House"]/a')))
        try:
            for url in driver.find_elements(By.XPATH,'//div[@itemtype="http://schema.org/House"]/a'):
                urls.append(url.get_attribute('href'))
        except StaleElementReferenceException:
            print('Append error')
        #WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.XPATH,"//a[@data-page='next']")))
        #next_button=driver.find_element(By.XPATH,"//a[@data-page='next']")
        #next_button.click()
   
    except NoSuchElementException:
        print('scraping done')

driver.quit()

In [35]:
len(urls)

110

In [41]:
for url in urls:  # Iterating each and every URL to fetch full details
    driver.get(url)  # Taking each URL one by one as an input
    sleep(1)

    # BHK_type 
    try:
        bhk = driver.find_element(By.XPATH, "//div[@class='css-1hidc9c']")
        BHK_type.append(bhk.text)
    except:
        BHK_type.append('None')

    # BEDS 
    try:
        beds_ = driver.find_element(By.XPATH, '//div[@class="flexbox hidden-mobile"]/div[2]/div[1]')
        beds.append(beds_.text)
    except:
        beds.append('None')

    # Bathroom
    try:
        bathr = driver.find_element(By.XPATH, '//div[@class="flexbox hidden-mobile"]/div[3]/div[1]')
        bath.append(bathr.text)
    except:
        bath.append('None')

    # Carpet area
    try:
        carea = driver.find_element(By.XPATH, '//div[@class="flexbox hidden-mobile"]/div[4]/div[1]')
        carpet_area.append(carea.text)
    except:
        carpet_area.append('None')

    # Price per square feet
    try:
        PRSF = driver.find_element(By.XPATH, '//div[@class="flexbox hidden-mobile"]/div[5]/div[1]')
        price_per_square_feet.append(PRSF.text)
    except:
        price_per_square_feet.append('None')

    # Property_Type
    try:
        pro = driver.find_element(By.XPATH, '//div[@class="outer-parameters-block"]/ul/li[2]/div[2]')
        property_type.append(pro.text)
    except:
        property_type.append('None')

    # Status
    try:
        sta = driver.find_element(By.XPATH, '//div[@class="outer-parameters-block"]/ul/li[8]/div[2]')
        status.append(sta.text if sta.text == 'Active' else 'None')
    except:
        status.append('None')

    # Year Built
    try:
        Year = driver.find_element(By.XPATH, '//div[@class="outer-parameters-block"]/ul/li[10]/div[2]')
        year_text = Year.text.strip()
        
        if year_text.isdigit() and len(year_text) == 4:
            year_built.append(int(year_text))
        else:
            year_built.append('None')  # Append 'NaN' if not a valid year
    except:
        year_built.append('None')


    # Landmarks
    try:
        land = driver.find_element(By.XPATH, '//div[@class="outer-parameters-block"]/ul/li[5]/div[2]')
        landmark.append(land.text)
    except:
        landmark.append('None')

    # Balcony
    try:
        bal = driver.find_element(By.XPATH, '//div[@data-testid="property-features-block"]/div[2]/ul/li[1]')
        balcony.append(Balc.text if Balc.text == 'Balcony' else 'None')
    except:
        balcony.append('None')

    # Address
    try:
        addr = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[1]')
        address.append(addr.text)
    except:
        address.append('None')

    # City
    try:
        city_ = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        city_text = city_.text.split(',')[0]  # Split the text by comma and get the first part
        city.append(city_text)
    except:
        city.append('None')

    # State_code
    try:
        State_cod = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[2]')
        State_code_ = State_cod.text.split(',')[1].strip()  # Split the text by comma and get the second part
        state_code.append(State_code_)
    except:
        state_code.append('None')

    # Country
    try:
        Addr = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        country.append(Addr.text)
    except:
        country.append('United States')

    # Floor
    try:
        f = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        floor.append(f.text)
    except:
        floor.append('None')

    # Transaction type
    try:
        trans = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        transaction_type.append(trans.text)
    except:
        transaction_type.append('None')

    # Furnished status
    try:
        furnish = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        furnished_status.append(furnish.text)
    except:
        furnished_status.append('None')

    # Facing
    try:
        fac = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        facing.append(fac.text)
    except:
        facing.append('None')

    # Car Parking
    try:
        car_par = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        car_parking.append(Car_par.text)
    except:
        car_parking.append('None')

    # Type of ownership
    try:
        Type_of_owners = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        type_of_ownership.append(Type_of_owners.text)
    except:
        type_of_ownership.append('None')

    # Booking amount
    try:
        booking = driver.find_element(By.XPATH, '//h1[@class="property-title-wrapper"]/span[10]')
        booking_amount.append(booking.text)
    except:
        booking_amount.append('None')

    # Buy total price
    try:
        buy_t = driver.find_element(By.XPATH, '//div[@class="flexbox hidden-mobile"]/div[1]/div[2]')
        price_usd = buy_t.text.replace('$', '').replace(',', '')  # Remove '$' and ','
        price_inr = round(float(price_usd) * 83.12)  # Convert to float and multiply by conversion rate
        buy_total_price.append(f'{price_inr:}')  # Format the output as INR
    except:
        buy_total_price.append('None')
        
        
    
# Quit WebDriver
driver.quit()

In [45]:
df11=pd.DataFrame({
    "BHK_type": beds,
    "Beds": beds,
    "Bathroom": bath,
    "Carpet_area": carpet_area,
    "Price_per_square_feet": price_per_square_feet,
    "Property_Type": property_type,
    "Status": status,
    "Year_Built": year_built,
    "Landmarks": landmark,
    "Balcony": balcony,
    "Address": address,
    "City": city,
    "State_Code": state_code,
    "Country": country,
    "Floor": floor,
    "Transaction_Type": transaction_type,
    "Furnished_Status": furnished_status,
    "Facing": facing,
    "Car_Parking": car_parking,
    "Type_of_Ownership": type_of_ownership,
    "Booking_Amount": booking_amount,
    "Buy_Total_Price": buy_total_price
})

In [46]:
df11

,BHK_type,Beds,Bathroom,Carpet_area,Price_per_square_feet,Property_Type,Status,Year_Built,Landmarks,Balcony,...,State_Code,Country,Floor,Transaction_Type,Furnished_Status,Facing,Car_Parking,Type_of_Ownership,Booking_Amount,Buy_Total_Price
0,2,2,1,None,None,Condo,Active,None,CHI - Near North Side,None,...,IL 60610,United States,None,None,None,None,None,None,None,33239688
1,4,4,3,0.07,None,Homes (Single Family),None,None,CHI - Lincoln Park,None,...,IL 60614,United States,None,None,None,None,None,None,None,73561200
2,3,3,1.5,None,None,Condo,None,None,Cook,None,...,IL 60657,United States,None,None,None,None,None,None,None,35326000
3,2,2,2,None,None,Condo,Active,1913,CHI - Loop,None,...,IL 60606,United States,None,None,None,None,None,None,None,33248000
4,5,5,3.5,"2,800",223,Condo,None,None,Cook,None,...,IL 60642,United States,None,None,None,None,None,None,None,51950000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,1,1,1,850,241,Condo,Active,1962,CHI - Near North Side,None,...,IL 60611,United States,None,None,None,None,None,None,None,17039600
106,2,2,2,"1,041",245,Condo,Active,1902,CHI - Near West Side,None,...,IL 60607,United States,None,None,None,None,None,None,None,21187288
107,3,3,2,None,None,Condo,Active,2001,CHI - Near North Side,None,...,IL 60654,United States,None,None,None,None,None,None,None,56106000
108,2,2,2,"1,200",250,Condo,Active,None,CHI - Irving Park,None,...,IL 60618,United States,None,None,None,None,None,None,None,24936000
109,1,1,1,None,None,Condo,Active,1972,CHI - Near North Side,None,...,IL 60611,United States,None,None,None,None,None,None,None,23689200

In [47]:
df11.to_csv('Chicago.csv', index=False)

In [70]:
import pandas as pd

# Read the tables
t1 = pd.read_csv('Bangalore.csv')
t2 = pd.read_csv('Gurgaon.csv')
t3 = pd.read_csv('Delhi.csv')
t4 = pd.read_csv('Chennai.csv')
t5 = pd.read_csv('Pune.csv')
t6 = pd.read_csv('Mumbai.csv')
t7 = pd.read_csv('Noida.csv')
t8 = pd.read_csv('Ghaziabad.csv')
t9 = pd.read_csv('Faridabad.csv')
t10 = pd.read_csv('Greater_Noida.csv')
t11 = pd.read_csv('Chicago.csv')

# Select the columns from each table
selected_columns_table1 = t1[['BHK_type','Property_Type', 'Beds', 'Bathroom', 'Balcony', 'Address','City','State_Code','Country' ,'Landmarks']]
selected_columns_table2 = t2[['BHK_type','Property_Type', 'Beds', 'Bathroom', 'Balcony', 'Address','City','State_Code','Country' ,'Landmarks']]
selected_columns_table3 = t3[['BHK_type','Property_Type', 'Beds', 'Bathroom', 'Balcony', 'Address','City','State_Code','Country' ,'Landmarks']]
selected_columns_table4 = t4[['BHK_type','Property_Type', 'Beds', 'Bathroom', 'Balcony', 'Address','City','State_Code','Country' ,'Landmarks']]
selected_columns_table5 = t5[['BHK_type','Property_Type', 'Beds', 'Bathroom', 'Balcony', 'Address','City','State_Code','Country' ,'Landmarks']]
selected_columns_table6 = t6[['BHK_type','Property_Type', 'Beds', 'Bathroom', 'Balcony', 'Address','City','State_Code','Country' ,'Landmarks']]
selected_columns_table7 = t7[['BHK_type','Property_Type', 'Beds', 'Bathroom', 'Balcony', 'Address','City','State_Code','Country' ,'Landmarks']]
selected_columns_table8 = t8[['BHK_type','Property_Type', 'Beds', 'Bathroom', 'Balcony', 'Address','City','State_Code','Country' ,'Landmarks']]
selected_columns_table9 = t9[['BHK_type','Property_Type', 'Beds', 'Bathroom', 'Balcony', 'Address','City','State_Code','Country' ,'Landmarks']]
selected_columns_table10 = t10[['BHK_type','Property_Type', 'Beds', 'Bathroom', 'Balcony', 'Address','City','State_Code','Country' ,'Landmarks']]
selected_columns_table11 = t11[['BHK_type','Property_Type', 'Beds', 'Bathroom', 'Balcony', 'Address','City','State_Code','Country' ,'Landmarks']]


table1 = pd.concat([selected_columns_table1, selected_columns_table2,selected_columns_table3,
                   selected_columns_table4,selected_columns_table5,selected_columns_table6,
                   selected_columns_table7,selected_columns_table8,selected_columns_table9,
                   selected_columns_table10,selected_columns_table11], axis=0).reset_index(drop=True)
table1.insert(0, 'Serial_Number', table1.index + 1)

# Save the new DataFrame to a CSV file or display it
table1.to_csv('table1.csv', index=False)
print(table1)

      Serial_Number  BHK_type        Property_Type  Beds  Bathroom  Balcony  \
0                 1         2    Sapthagiri Palace     2       2.0      2.0
1                 2         3   Pjc Royale Arcadia     3       2.0      2.0
2                 3         3             Nd Sepal     3       3.0      2.0
3                 4         4  Standalone Building     4      17.0      8.0
4                 5         4    Independent House     4       7.0      2.0
...             ...       ...                  ...   ...       ...      ...
2990           2991         1                Condo     1       1.0      NaN
2991           2992         2                Condo     2       2.0      NaN
2992           2993         3                Condo     3       2.0      NaN
2993           2994         2                Condo     2       2.0      NaN
2994           2995         1                Condo     1       1.0      NaN

                                                Address       City State_Code  \
0                                     Sapthagiri Palace  Bangalore         KA
1     27th Cross Road, ITI Layout, Sector 2, HSR Lay...  Bangalore         KA
2                           Somasundarapalya, Bangalore  Bangalore         KA
3     Standalone Building, Off Haralur Road near Ken...  Bangalore         KA
4              Independent House, Behind Bank of Baroda  Bangalore         KA
...                                                 ...        ...        ...
2990                    535 North Michigan Avenue #2212    Chicago   IL 60611
2991                      500 South Clinton Street #342    Chicago   IL 60607
2992                       630 North State Street #2301    Chicago   IL 60654
2993                       3012 West Addison Street #4S    Chicago   IL 60618
2994                      111 East Chestnut Street #26B    Chicago   IL 60611

            Country                      Landmarks
0             India  H S R Layout (Pickup Van/Bus)
1             India        Narasimha Chitramandira
2             India                Barbeque Nation
3             India        Narasimha Chitramandira
4             India                Barbeque Nation
...             ...                            ...
2990  United States          CHI - Near North Side
2991  United States           CHI - Near West Side
2992  United States          CHI - Near North Side
2993  United States              CHI - Irving Park
2994  United States          CHI - Near North Side

[2995 rows x 11 columns]

In [71]:
table1

,Serial_Number,BHK_type,Property_Type,Beds,Bathroom,Balcony,Address,City,State_Code,Country,Landmarks
0,1,2,Sapthagiri Palace,2,2.0,2.0,Sapthagiri Palace,Bangalore,KA,India,H S R Layout (Pickup Van/Bus)
1,2,3,Pjc Royale Arcadia,3,2.0,2.0,"27th Cross Road, ITI Layout, Sector 2, HSR Lay...",Bangalore,KA,India,Narasimha Chitramandira
2,3,3,Nd Sepal,3,3.0,2.0,"Somasundarapalya, Bangalore",Bangalore,KA,India,Barbeque Nation
3,4,4,Standalone Building,4,17.0,8.0,"Standalone Building, Off Haralur Road near Ken...",Bangalore,KA,India,Narasimha Chitramandira
4,5,4,Independent House,4,7.0,2.0,"Independent House, Behind Bank of Baroda",Bangalore,KA,India,Barbeque Nation
...,...,...,...,...,...,...,...,...,...,...,...
2990,2991,1,Condo,1,1.0,NaN,535 North Michigan Avenue #2212,Chicago,IL 60611,United States,CHI - Near North Side
2991,2992,2,Condo,2,2.0,NaN,500 South Clinton Street #342,Chicago,IL 60607,United States,CHI - Near West Side
2992,2993,3,Condo,3,2.0,NaN,630 North State Street #2301,Chicago,IL 60654,United States,CHI - Near North Side
2993,2994,2,Condo,2,2.0,NaN,3012 West Addison Street #4S,Chicago,IL 60618,United States,CHI - Irving Park
2994,2995,1,Condo,1,1.0,NaN,111 East Chestnut Street #26B,Chicago,IL 60611,United States,CHI - Near North Side

In [73]:
# Read the tables
t1 = pd.read_csv('Bangalore.csv')
t2 = pd.read_csv('Gurgaon.csv')
t3 = pd.read_csv('Delhi.csv')
t4 = pd.read_csv('Chennai.csv')
t5 = pd.read_csv('Pune.csv')
t6 = pd.read_csv('Mumbai.csv')
t7 = pd.read_csv('Noida.csv')
t8 = pd.read_csv('Ghaziabad.csv')
t9 = pd.read_csv('Faridabad.csv')
t10 = pd.read_csv('Greater_Noida.csv')
t11 = pd.read_csv('Chicago.csv')

# Select the columns from each table
selected_columns_table1 = t1[['Carpet_area','Status' ,'Floor' ,'Transaction_Type', 'Year_Built', 'Price_per_square_feet']]
selected_columns_table2 = t2[['Carpet_area','Status' ,'Floor' ,'Transaction_Type', 'Year_Built', 'Price_per_square_feet']]
selected_columns_table3 = t3[['Carpet_area','Status' ,'Floor' ,'Transaction_Type', 'Year_Built', 'Price_per_square_feet']]
selected_columns_table4 = t4[['Carpet_area','Status' ,'Floor' ,'Transaction_Type', 'Year_Built', 'Price_per_square_feet']]
selected_columns_table5 = t5[['Carpet_area','Status' ,'Floor' ,'Transaction_Type', 'Year_Built', 'Price_per_square_feet']]
selected_columns_table6 = t6[['Carpet_area','Status' ,'Floor' ,'Transaction_Type', 'Year_Built', 'Price_per_square_feet']]
selected_columns_table7 = t7[['Carpet_area','Status' ,'Floor' ,'Transaction_Type', 'Year_Built', 'Price_per_square_feet']]
selected_columns_table8 = t8[['Carpet_area','Status' ,'Floor' ,'Transaction_Type', 'Year_Built', 'Price_per_square_feet']]
selected_columns_table9 = t9[['Carpet_area','Status' ,'Floor' ,'Transaction_Type', 'Year_Built', 'Price_per_square_feet']]
selected_columns_table10 = t10[['Carpet_area','Status' ,'Floor' ,'Transaction_Type', 'Year_Built', 'Price_per_square_feet']]
selected_columns_table11 = t11[['Carpet_area','Status' ,'Floor' ,'Transaction_Type', 'Year_Built', 'Price_per_square_feet']]


table2 = pd.concat([selected_columns_table1, selected_columns_table2,selected_columns_table3,
                   selected_columns_table4,selected_columns_table5,selected_columns_table6,
                   selected_columns_table7,selected_columns_table8,selected_columns_table9,
                   selected_columns_table10,selected_columns_table11], axis=0).reset_index(drop=True)
table2.insert(0, 'Serial_Number', table1.index + 1)

# Save the new DataFrame to a CSV file or display it
table2.to_csv('table2.csv', index=False)

In [74]:
table2

,Serial_Number,Carpet_area,Status,Floor,Transaction_Type,Year_Built,Price_per_square_feet
0,1,NaN,"Jun 25, 2024",NaN,NaN,NaN,NaN
1,2,1300.0,"Jun 29, 2024",4/5,NaN,NaN,NaN
2,3,NaN,"Jun 27, 2024",NaN,NaN,NaN,NaN
3,4,NaN,"Jun 25, 2024",NaN,NaN,NaN,NaN
4,5,NaN,"Jul 6, 2024",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
2990,2991,850,Active,NaN,NaN,1962.0,241
2991,2992,"1,041",Active,NaN,NaN,1902.0,245
2992,2993,NaN,Active,NaN,NaN,2001.0,NaN
2993,2994,"1,200",Active,NaN,NaN,NaN,250
2994,2995,NaN,Active,NaN,NaN,1972.0,NaN

In [75]:
# Read the tables
t1 = pd.read_csv('Bangalore.csv')
t2 = pd.read_csv('Gurgaon.csv')
t3 = pd.read_csv('Delhi.csv')
t4 = pd.read_csv('Chennai.csv')
t5 = pd.read_csv('Pune.csv')
t6 = pd.read_csv('Mumbai.csv')
t7 = pd.read_csv('Noida.csv')
t8 = pd.read_csv('Ghaziabad.csv')
t9 = pd.read_csv('Faridabad.csv')
t10 = pd.read_csv('Greater_Noida.csv')
t11 = pd.read_csv('Chicago.csv')

# Select the columns from each table
selected_columns_table1 = t1[['Furnished_Status', 'Facing' , 'Car_Parking', 'Type_of_Ownership' ,'Booking_Amount' ,'Buy_Total_Price']]
selected_columns_table2 = t2[['Furnished_Status', 'Facing' , 'Car_Parking', 'Type_of_Ownership' ,'Booking_Amount' ,'Buy_Total_Price']]
selected_columns_table3 = t3[['Furnished_Status', 'Facing' , 'Car_Parking', 'Type_of_Ownership' ,'Booking_Amount' ,'Buy_Total_Price']]
selected_columns_table4 = t4[['Furnished_Status', 'Facing' , 'Car_Parking', 'Type_of_Ownership' ,'Booking_Amount' ,'Buy_Total_Price']]
selected_columns_table5 = t5[['Furnished_Status', 'Facing' , 'Car_Parking', 'Type_of_Ownership' ,'Booking_Amount' ,'Buy_Total_Price']]
selected_columns_table6 = t6[['Furnished_Status', 'Facing' , 'Car_Parking', 'Type_of_Ownership' ,'Booking_Amount' ,'Buy_Total_Price']]
selected_columns_table7 = t7[['Furnished_Status', 'Facing' , 'Car_Parking', 'Type_of_Ownership' ,'Booking_Amount' ,'Buy_Total_Price']]
selected_columns_table8 = t8[['Furnished_Status', 'Facing' , 'Car_Parking', 'Type_of_Ownership' ,'Booking_Amount' ,'Buy_Total_Price']]
selected_columns_table9 = t9[['Furnished_Status', 'Facing' , 'Car_Parking', 'Type_of_Ownership' ,'Booking_Amount' ,'Buy_Total_Price']]
selected_columns_table10 = t10[['Furnished_Status', 'Facing' , 'Car_Parking', 'Type_of_Ownership' ,'Booking_Amount' ,'Buy_Total_Price']]
selected_columns_table11 = t11[['Furnished_Status', 'Facing' , 'Car_Parking', 'Type_of_Ownership' ,'Booking_Amount' ,'Buy_Total_Price']]


table3 = pd.concat([selected_columns_table1, selected_columns_table2,selected_columns_table3,
                   selected_columns_table4,selected_columns_table5,selected_columns_table6,
                   selected_columns_table7,selected_columns_table8,selected_columns_table9,
                   selected_columns_table10,selected_columns_table11], axis=0).reset_index(drop=True)
table3.insert(0, 'Serial_Number', table1.index + 1)

# Save the new DataFrame to a CSV file or display it
table3.to_csv('table3.csv', index=False)

In [76]:
table3

,Serial_Number,Furnished_Status,Facing,Car_Parking,Type_of_Ownership,Booking_Amount,Buy_Total_Price
0,1,NaN,NaN,Car,Self Owned,NaN,5300000.0
1,2,NaN,North,Bike and Car,Self Owned,NaN,19000000.0
2,3,NaN,NaN,Bike and Car,Self Owned,NaN,10500000.0
3,4,NaN,NaN,Car,Self Owned,NaN,53000000.0
4,5,NaN,NaN,Bike and Car,Self Owned,NaN,37500000.0
...,...,...,...,...,...,...,...
2990,2991,NaN,NaN,NaN,NaN,NaN,17039600.0
2991,2992,NaN,NaN,NaN,NaN,NaN,21187288.0
2992,2993,NaN,NaN,NaN,NaN,NaN,56106000.0
2993,2994,NaN,NaN,NaN,NaN,NaN,24936000.0
2994,2995,NaN,NaN,NaN,NaN,NaN,23689200.0

In [2]:
import mysql.connector 
mydb=mysql.connector.connect(
    host='localhost',
    user='root',
    password='root'
)
print(mydb)

<mysql.connector.connection_cext.CMySQLConnection object at 0x00000255740935D0>

In [4]:
#check database
mycursor = mydb.cursor()

mycursor.execute('SHOW DATABASEs')

for x in mycursor:
    print(x)

('information_schema',)
('insurance',)
('mysql',)
('performance_schema',)
('properties',)
('sakila',)
('sys',)
('task',)
('world',)

In [6]:
sql="SELECT City,count(*) AS property_count FROM properties.table1 group by City"

mycursor.execute(sql)
myresult = mycursor.fetchall()
for x in myresult:
    print(x)

('Bangalore', 375)
('Gurgaon', 190)
('Delhi', 120)
('Chennai', 160)
('Pune', 153)
('Mumbai', 165)
('Noida', 133)
('Ghaziabad', 119)
('Faridabad', 36)
('Greater Noida', 408)